### ISSUE TITLE
Is this project contribution allowed?

### ISSUE THREAD

**Issue by simsim0709** [material-components/material-components-web-react#105]
It seems like this project is actively developing.

I'm wondering if contribution is allowed for anyone interested in this project.

Thank you.

**Comment by moog16** [comment]
@simsim0709 yes definitely! Much appreciated and encouraged. There is one caveat: if you do any large changes please run them by one of the core contributors with admin rights. It would be a shame if you do a ton of work without running it by us, and we don't like it.

What is a large change (you might ask)?

It definitely depends. If you're in doubt please run it by us anyways. The more communication you have with us the better chance of your contribution making it in.
