### ISSUE TITLE
Please don’t publish experimental syntax on npm

### ISSUE THREAD

**Issue by gaearon** [material-components/material-components-web-react#107]
Hi, I help maintain React and some other projects like Create React App. 👋

I recently saw in this issue (https://github.com/facebook/create-react-app/issues/4648#issuecomment-398540069) that this project uses experimental syntax (such as class properties) as part of the npm entry point.

I strongly encourage you to reconsider this decision. If the class properties transform ends up changing (which is very likely) or abandoned (not as likely, but could happen), having uncompiled packages on npm using it will create a huge amount of churn for everyone (including maintainers of this project). Not to mention this makes the project unusable in any environment that respects the spec (such as Node.js).

Please compile any experimental syntax away before publishing. If you’re convinced that keeping `import` uncompiled is worth it (which is a whole separate can of worms as you can see in https://github.com/graphql/graphql-js/issues/1248), please **compile at least the non-standard syntax away when publishing**. That includes JSX too. 

I understand this might seem like an inconvenience now. But it will be much better to do now than deal with pain for months when build tools and the spec changes. Thanks.

**Comment by gaearon** [comment]
To be clear, it's totally possible with Babel to keep the import/export in the bundle (if you consider it worth the Node compatibility issues until `mjs` shakes out), but compile the rest of the syntax. Many React projects already do that, and I'd be happy to help in case you have any issues with this approach.

**Comment by moog16** [comment]
@gaearon you are suggesting that we switch our npm entry point to transpiled ES5 syntax? Kind of like what this [issue](https://github.com/material-components/material-components-web-react/issues/100) is talking about. We do provide a non experimental syntax version as mentioned in the issue.

**Comment by gaearon** [comment]
I think that would be a great first step!

But my understanding is that you still *want* to provide a source version so I'd love to learn why. If it's just for better tree shaking with e.g. webpack, then you could provide a version with `import`/`export` (but still no experimental syntax) instead.

**Comment by gaearon** [comment]
In particular, my concern is that publishing the source code (even as an optional other entry point) will encourage people to use it (e.g. because they think it will make their app smaller) and cause issues for the ecosystem when it starts switching to incompatible tooling. For example, even Babel 6 and Babel 7 handle class properties differently by default. And the spec isn't even finalized yet.

**Comment by moog16** [comment]
Yes that was our initial thought. I'll bring this to the team in the morning so that we're all on the same page to reach a consensus. But my thinking right now is at the very least updating the npm entry points for the packages.

**Comment by gaearon** [comment]
Thanks! I'm always happy to chat about this, feel free to ping me anytime.

I care about this because I've seen people burned by this multiple times (e.g. Babel 5 -> Babel 6 transition, RN upgrades), and unfortunately the people who suffer the most are usually beginners who just followed a tutorial and can't fix anything in a third-party package.

Your fast response is very much appreciated!

**Comment by hzoo** [comment]
Happy to chat as well (slack/hangouts) if you need to talk through something too (I help maintain Babel).
