### ISSUE TITLE
RippledComponent warning: Can't call setState (or forceUpdate) on an unmounted component

### ISSUE THREAD

**Issue by bmihelac** [material-components/material-components-web-react#111]
When Button is unmounted, React will produce warning as bellow:

```
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in RippledComponent (created by App)
```

Here is minimal test case that would produce warning when button is clicked:
https://codesandbox.io/s/9zw5v67kn4

**Comment by moog16** [comment]
Thanks for opening this issue. I never noticed it before. I saw @lucasecdb open a PR, but I want to do some investigation of my own before moving forward with his PR.

**Comment by WilliamBewzenko** [comment]
There is another issue related
```
TypeError: Cannot read property 'getBoundingClientRect' of null
```

https://github.com/material-components/material-components-web-react/blob/a53fc7dc77ffb89bc0e58260752aa3b2540bbfbe/packages/ripple/index.js#L58

**Comment by moog16** [comment]
@WilliamBewzenko are you using the withRipple() HOC? In the docs we state you need to pass `initRipple` into the ref.

**Comment by WilliamBewzenko** [comment]
@moog16 I am using as HOC, but the problem is occurring in the Button component, when I click I redirect it to another page, with this the ripple effect is still occurring, but the component has already been given unmount

**Comment by moog16** [comment]
@WilliamBewzenko so 2 issues are happening:

1. cannot call setState from unmounted component (Ripple)
1. cannot read property 'getBoundingClientRect' of null (Button)

Is this correct?

**Comment by lucasecdb** [comment]
@moog16 I think both errors are on the ripple component. I had a similar error when I was testing the changes I made on my PR, although I think once the setState error is resolved, the instance being null will be too.

I could also add to my PR the check for the `unmounted_` on this method.

**Comment by bmihelac** [comment]
I think that this is broader issue that would repeat with other components as well in similar situations. From what I understand this is what happens:

1. When Interacting with material components, they initiate changes to be made by adapter like updating css classes, attributes and styles of component underneath HTML elements as well as requesting value of some attributes and properties. For animation this changes can take some time. 

2. If same interaction makes React component to be unmounted before foundation is over with what it is doing, various warnings/errors could be produced as adapter tries to set state and update/read underneath HTML elements class, styles, attributes.

Adapter methods that manipulate state or update/read underneath HTML elements should probably be shortcircuted when component is unmounted. Maybe it would be great to have this extracted to some util functions so every react component does not have to do same checks over and over again.

**Comment by moog16** [comment]
@lucasecdb I've taken a look at your PR, but I'm suspecting that it is an issue across the board. Similar to what @bmihelac is saying, so I want to investigate before reaching any conclusions. I just haven't had the time (not ignoring this issue).

**Comment by lucasecdb** [comment]
@moog16 that's fine! look into it when you can, but I agree with you and @bmihelac that this is a broader issue that requires a more in-depth analysis.
