### ISSUE TITLE
The README is missing a section on how to install material-components-web-react

### ISSUE THREAD

**Issue by mugwump** [material-components/material-components-web-react#114]
the [README](https://github.com/material-components/material-components-web-react/blob/master/README.md) is pretty elaborate on how to install react and sass - but its missing the crucial part of how to actually install ```material-components-web-react``` - the simple ```npm i --save material-components-web-react``` only brings up an outdated version (0.0.10), which is missing most of the components except button and checkbox.

**Comment by moog16** [comment]
@mugwump this repo is not the same as this repo: https://github.com/MihirNS/material-components-web-react. Our npm url is https://www.npmjs.com/package/@material/react-text-field. 

Also the instructions for each package is within each directory of the package, ie. https://github.com/material-components/material-components-web-react/blob/master/packages/text-field/README.md.

**Comment by mugwump** [comment]
I figured that out after some trial&error that you had to install individual components instead of installing the whole package and then referencing components. I understand the rationale behind this, but a short note in the Readme of the main-project would probably help people to get started...

**Comment by moog16** [comment]
Are you talking about the MDC-Web repo: https://github.com/material-components/material-components-web?

**Comment by nickmccurdy** [comment]
Does this help? #137

**Comment by mugwump** [comment]
yes, this makes it much much clearer and avoids the confusion with all the likely-sounding libs out there. +1 for the commit!

**Comment by moog16** [comment]
Thanks for opening the PR!
