### ISSUE TITLE
Plans for implementing more  Components?!

### ISSUE THREAD

**Issue by mugwump** [material-components/material-components-web-react#115]
material-components-web-react currently implements only the very basic components (Button, Checkbox) - is there a roadmap, when the other components will be implemented? Or is there a contribution-guide, that explains how adding a new component is supposed to work?

**Comment by jimbojetlag** [comment]
It would be helpful if the table in the README file can be extended to include components to be wrapped.

**Comment by lynnjepsen** [comment]
I've added a [roadmap](https://github.com/material-components/material-components-web-react/blob/master/ROADMAP.md) and a [contributing guide](https://github.com/material-components/material-components-web-react/blob/master/CONTRIBUTING.md). We will try and keep the table in the README up to date as we wrap new components
