### ISSUE TITLE
Add support for <textarea> (just like in MDC Web)

### ISSUE THREAD

**Issue by jimbojetlag** [material-components/material-components-web-react#118]
Is `TextField` supposed to wrap `textarea` instead of the provided `Input` when the prop `textarea` is set to `true`?

Will there be also a wrapper for `textarea` similar to `Input`?

**Comment by qpjsir** [comment]
厉害了

**Comment by moog16** [comment]
Originally the idea was to add a `<TextArea>` component similar to `<Input>`. There were some issues with the core repo that we had with textarea at the time, so we skipped it during launch. We will need to circle back and add in this component.

For the time being I think it is possible to just use a regular `<textarea>` element. Would it work if I added an example of that in the docs?

**Comment by jimbojetlag** [comment]
A working example with regular `<textarea>` would be useful. I ran into difficulties with this approach, had to copy/paste the source code for `<Input>` and replace the `<input>` tag with `<textarea>` to get it working.

**Comment by moog16** [comment]
Got it. I'll try getting a working example working and then update the docs.

**Comment by moog16** [comment]
While chatting on Discord, a user explained that the outlined and textarea props will trigger a double outline. The intention is to only use the textarea prop. Whatever is documented on MDCW should also be documented here.
