### ISSUE TITLE
Trouble to understand how to use only 1 class generator

### ISSUE THREAD

**Issue by guillaumebreux** [material-components/material-components-web-react#124]
Hi there,

I have some kind of flickering when I do ssr with my app and I think it is due to the fact that the generated class are different from the server and the client side. (The content from the `view source` and the one from `document.documentElement.innerHTML` are different, but I don't have any react warnings)

[As I can see in your documentation](https://material-ui.com/guides/server-rendering/#react-class-name-hydration-mismatch), a possible action to take would be to use the same generator: `The whole page needs to be rendered with a single generator.`

However, i do not understand how I should do that..

Here is the how I render server side:
```
const sheetsRegistry = new SheetsRegistry();
const generateClassName = createGenerateClassName();
renderToString(
          <Loadable.Capture report={m => modules.push(m)}>
            <Provider store={store}>
              <StaticRouter location={req.url} context={context}>
                <Frontload isServer>
                  <JssProvider registry={sheetsRegistry}
                               generateClassName={generateClassName}>
                    <MuiThemeProvider theme={overidedTheme}
                                      sheetsManager={new Map()}>
                      <CssBaseline/>
                      <App />
                    </MuiThemeProvider>
                  </JssProvider>
                </Frontload>
              </StaticRouter>
            </Provider>
          </Loadable.Capture>
        )
```
And Client side
```
const Application = (<Provider store={store}>
  <ConnectedRouter history={history}>
    <Frontload noServerRender>
      <MuiThemeProvider theme={overidedTheme}>
        <CssBaseline/>
        <Main />
      </MuiThemeProvider>
    </Frontload>
  </ConnectedRouter>
</Provider>);
Loadable.preloadReady().then(() => {
    hydrate(Application, root);
  });
```

When I compare the outputs, the difference are coming from the class names and the positions of the `style` tags (client side has multiple style tag inside the head while the server side has only one big style tag at the end before the body)

I would love to understand what could be the cause of this problem and how I can solve it!

Thanks :)

**Comment by moog16** [comment]
@guillaumebreux which documentation are you referring to? That link is a 404.

Yes if class names or inline styles are appearring/not appearing then that is probably the cause of your issue. However our repo does not have control over the position of style tags within your app (before/after body tag). That sounds like something on your end, since this repo only focuses on building components. 

I also see that you are using JSS. Possibly...JSS is renaming classes that MDC is using. Its hard to say without seeing an example of what issues you are encountering. Do you have an example that you can share?

**Comment by moog16** [comment]
Closing - no response

**Comment by guillaumebreux** [comment]
Sorry for my very late reply, the project I was working on was temporary set aside.

Now I could take a fresh look on it after a month, I finally fixed my issue. It wasn't related to material-ui at all:

It was due to the fact that I used react-loadable and failed at injecting the Loadable component before the main Js build.

Anyway, thanks for your answer and sorry for the late reply :)

**Comment by moog16** [comment]
no worries - glad you got it all working :)
