### ISSUE TITLE
Add Select

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#128]
Add a new select component to mirror MDC Web's Select.

https://github.com/material-components/material-components-web/tree/v0.37.0/packages/mdc-select

**Comment by manishbisht** [comment]
Hi, I would like to take this up if no one is working on this. :smile:

**Comment by moog16** [comment]
Hey @manishbisht no one is working on this just yet, but it is a new component. This will make the change set larger than usual. Since we're so new I don't think we want to take new components from the community just yet. I anticipate that the back and forth will create more work than just building it internally. 

I assume you might need this component for one of your projects, but we are planning on finishing this component by end of the month. Does that work for you?

**Comment by manishbisht** [comment]
I have not yet started using this library on any of my projects but planning to use in future. :smile:

Actually as this project is recently started so thinking to make this complete/better by contributing to it. If you want to build this internally no issues then you can redirect me to other issues that I can fix.
