### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#132]
Steps to reproduce:

1. start screenshot tests on IE11

Actual Result: Syntax error around withRipple HOC

Expected: Working - no syntax error

I think what is happening is the webpack config is not transpiling some ES6 code --> ES5 like we expect it to.

**Comment by kfranqueiro** [comment]
One thing I noticed is ripple is using `Object.assign` but I don't see `babel-plugin-transform-object-assign` in deps - is that needed? I don't think that would cause a syntax error though...

**Comment by moog16** [comment]
I believe the babel-polyfill comes with that. I thought that the babel-polyfill had all the missing ES5 features, but the version we had in this repo was missing a few. So I decided to revert from env.
