### ISSUE TITLE
Create icon button

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web-react#143]
See the MDC Web version we will wrap: 
https://github.com/material-components/material-components-web/tree/master/packages/mdc-icon-button

**Comment by kfranqueiro** [comment]
Just FYI, I would point out https://github.com/material-components/material-components-web/issues/3107 will affect this component's DOM structure when we pursue it (and we will likely want to pursue it sometime soon to support clients that want SVG-powered toggle buttons).

Not saying it can't be wrapped before then, just that it may need an update a couple of months from now.
