### ISSUE TITLE
Write a best practices doc around deeply nested state

### ISSUE THREAD

**Issue by lynnmercier** [material-components/material-components-web-react#145]
In particular, classList is a Set, and we often change add/remove classes to this Set.

This best practices doc can also apply to deeply nested props. But note that className is a String, which is not deeply nested.

Best practices docs represent standards we hold for all new components. It also applies if we go back and modify an existing component...then we also have to bring that component in line with best practices. Basically we follow the campground rule of "leave it better than how you found it"

**Comment by moog16** [comment]
Stale issue. Closing
