### ISSUE TITLE
Update component readmes to point to `master` branch 

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#160]
Currently in most readmes, there is a reference to sass mixins. These all point to an older version of the component. They might be out of date, and should be changed to point to `master` instead.

**Comment by kfranqueiro** [comment]
Shouldn't they point to the latest release that MDC React is up-to-date with?

Pointing to `master` risks referencing documentation of unreleased features even in MDC Web, or features that are in a release that MDC React hasn't updated to yet.

**Comment by moog16** [comment]
That is true. I was thinking from a maintenance point of view it might be a lot of work. But I think if we also add it to the release steps then we at least won't forget.

Otherwise we could possibly write a script for that, but not sure if its worth the time.
