### ISSUE TITLE
Floating label on textfield overlaps with input value

### ISSUE THREAD

**Issue by Ranguna** [material-components/material-components-web-react#165]
The floating lable in a text field overlaps with the input text when it's removed and reset with onblur:

![peek 2018-07-23 12-03](https://user-images.githubusercontent.com/5003755/43073200-944ac392-8e70-11e8-8233-9d6891f89274.gif)

### Steps to reproduce
Create a text field with an onblur method that resets the value to something else:
``` js
import React, { Component } from 'react';
import TextField, {Input} from '@material/react-text-field';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {value:"hello"};
  }

  render() {
    return (
      <div className="App">

        <TextField outlined label='Label'>
          <Input
            value={this.state.value}
            onBlur={()=>this.setState({value:"Noooo"})}
            onChange={(e)=>this.setState({value:e.target.value})}
          />
        </TextField>
      </div>
    );
  }
}

export default App;
```
1. Delete all content in the input field
2. Press anywhere outside the text field
3. Let the bug happen

Maybe a fix could be to reuse the code that checks if there's text in the input when the text field is mounted (this is done to prevent the lable from overlaping the input text when it's mounted in case a value is set from the beginning) to check every time it blurs or every time the class changed to `--float-above` ?

**Comment by Ranguna** [comment]
Oh yeah nice and quick fix, great work :+1: 
Should this be closed now or when the PR gets merged ?

**Comment by moog16** [comment]
This seemed important and quick :) 

We'll leave it open until it is merged into master - Thanks again

**Comment by derektumulak** [comment]
I've just run this this issue with some of the fields that I'm using. I'm a bit of a newbie and wondering what the best way is for me to resolve this. Are there any recent best practices?

Thanks in advance!
-Derek

**Comment by moog16** [comment]
@derektumulak are you still running into this? A codepen/stackblitz will help in helping you.
