### ISSUE TITLE
react-ripple does not contain styles

### ISSUE THREAD

**Issue by eric-zeng** [material-components/material-components-web-react#172]
Getting this error when attempting to follow the example for react-ripple:

`Uncaught Error: Cannot find module '@material/react-ripple/index.scss'`

Looks like neither index.scss nor dist/ripple.css exists in the react-ripple npm package.

<img width="239" alt="screen shot 2018-07-24 at 12 59 12 am" src="https://user-images.githubusercontent.com/2206755/43124832-1d0af906-8edd-11e8-9f26-acba2e1689fb.png">

**Comment by moog16** [comment]
@eric-zeng you're right - we missed adding the index.scss file for ripple. In our screenshot tests we actually  import the sass from material-web. 

As a work around until we release again, you should be able to import the sass like so:

```scss
@import "@material/ripple/common";
@import "@material/ripple/mixins";
```

**Comment by moog16** [comment]
closing: https://github.com/material-components/material-components-web-react/pull/251
