### ISSUE TITLE
Add HelperText Usage Docs for use with validation prop

### ISSUE THREAD

**Issue by Ranguna** [material-components/material-components-web-react#177]
Hello,

I'm trying to get HelperText component to display as an error message like in material.io specs but I really don't know what props to set and when.

Also, if I set both `isValid` and `validation` to true, the helper text doesn't appear.
It's opacity is set to 0 (expected) but the transition isn't being run when I press the text field.

### Step to reproduce
Do the usual `create-react-app` setup and `npm install @material/helper-text`.
Import the sass file:
``` css
@import '@material/react-text-field/index.scss';
```
And use this App.js
``` js
import React, { Component } from 'react';
import TextField, {Input, HelperText} from '@material/react-text-field';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {value:"hello"};
  }

  render() {
    return (
      <div className="App">
        <TextField
          box
          label='Dog'
          helperText={<HelperText isValid validation>Help Me!</HelperText>}
        >
          <Input
            value={this.state.value}
            onChange={(e) => this.setState({value: e.target.value})}/>
        </TextField>
      </div>
    );
  }
}

export default App;
```

### Expected behaviour
The helper text to appear, ideally in a different color.

### What actually happens
Nothing, the text helper doesn't appear.

### How I'll handle it for now

I'll simply use it without setting any props and do the color logic on my side but it'd be helpful if the component did this by itself (trembling animations and all), since it has the proper props.

But maybe I'm I doing something wrong ?
Maybe I forgot to include some scss files or I'm missing a character somewhere ?

**Comment by moog16** [comment]
If you want it to appear always (persistent), you can add the `persistent` attr:

```
helperText={<HelperText isValid validation persistent>Help Me!</HelperText>}```

Does that help? Or is it supposed to be an error message?

**Comment by Ranguna** [comment]
Yes that will help too but it's supped to be an error message:
![image](https://user-images.githubusercontent.com/5003755/43248365-8ea008ee-90af-11e8-8f7e-81997328effa.png)

**Comment by moog16** [comment]
So the way the MDC Web version works is the helper text needs to have the `mdc-text-field-helper-text--validation-msg` class to have red colored text. Also the text-field element must have the `mdc-text-field--invalid` class. The way in which the react text field gets the `--invalid` class is by setting a validation property (pattern, min, max, require, step, minlength, maxlength). Example:
```
<TextField
          box
          label='Dog'
          helperText={<HelperText validation>Help Me!</HelperText>}
        >
          <Input
            value={this.state.value}
            minLength={8}
            onChange={(e) => this.setState({value: e.target.value})}/>
        </TextField>
```

**Comment by Ranguna** [comment]
Oh so HelperText needs to have the validation prop and input also needs to have at least on of the validation properties, noted :ok_hand: 
Maybe this should be added to the docs ?

**Comment by moog16** [comment]
It totally should...and thanks for bringing this to our attention. Its not as self evident as we hoped for. I'll leave this issue open for adding this to the docs.

**Comment by Ranguna** [comment]
Maybe it's just me since I didn't know that <input> had those attributes but I think it's best to have this in there.
I'll try to add them myself if I find the time.

**Comment by Ranguna** [comment]
Sorry for the delay, will do :ok_hand:

**Comment by moog16** [comment]
@Ranguna pinging this thread to see if you're still up for the job :)

**Comment by Ranguna** [comment]
Again sorry for the delay, pull request #221 up for review.
BTW I signed the CLA and gave the bot a thumbs up, is that enough or do I need to explicitly reply to the PR ?
