### ISSUE TITLE
Button calling setState when unmounted

### ISSUE THREAD

**Issue by Ranguna** [material-components/material-components-web-react#179]
Hey,

I just noticed that when I unmount a button, react throws the following error:
```
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

You can reproduce this by simply adding a button and removing it right afterwards like this:
``` javascript
import React, { Component } from 'react';
import Button from '@material/react-button/dist';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {show:true};
    process.nextTick(()=>this.setState({show:false}));
  }

  render() {
    return (
      <div className="App">
        {this.state.show && <Button>Button</Button>}
      </div>
    );
  }
}

export default App;
```
You could also wrap the state change in the button's onClick event:
``` javascript
{this.state.show && <Button onClick={()=>this.setState({show:false})}>Button</Button>}
```

Maybe I'm not supposed to unmount it this way ?

**Comment by moog16** [comment]
I believe this is an issue with the Ripple and has been fixed. It will be in the new release, but for now it probably going to show up as a warning. 

Is this the same issue you are seeing: https://github.com/material-components/material-components-web-react/issues/111?

**Comment by Ranguna** [comment]
Oh I missed that issue !
Yep it's the same warning.
Thank you and keep it up :+1:
