### ISSUE TITLE
ripple - TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by bmihelac** [material-components/material-components-web-react#199]
Sorry to open this, but it looks like issue that seemed mentioned in
https://github.com/material-components/material-components-web-react/issues/111#issuecomment-401171254 still exists.

Removing `TopAppBar` which includes `MaterialIcon` element produces TypeError:

```
index.js:124 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Object.computeBoundingRect (VM512 index.js:124)
    at MDCRippleFoundation.layoutInternal_ (VM512 index.js:482)
    at eval (VM512 index.js:441)
```

Here is a minimal test case - pressing *menu* will trigger TypeError:

https://codesandbox.io/s/721pv52661

Let me know if anything else is needed.

**Comment by bmihelac** [comment]
Thanks!

**Comment by moog16** [comment]
You could use lerna, but that requires a bit of configuration. Also not as ideal or clean, but for the time being before release you could just copy/paste. Are you using CRA? Or just a webpack setup? 

If you're using a custom webpack setup, you could setup the `externals` property, and then point to a cloned directory of @material/react-ripple. 

Any of those suggestions work for you?

**Comment by bmihelac** [comment]
Thanks for suggestions @moog16. I am using CRA and also wanted to quick check codesandbox test cases against fixed versions. 

Both without much success, the best I was able is to locally build and, run `node scripts/release/cp-pkgs.js` and then install local packages.

**Comment by moog16** [comment]
yup! all you really need is that `/dist` js file located after running `npm run build` and `node ./scripts/release/cp-pkgs.js`
