### ISSUE TITLE
No dense option on button

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#214]
Button is missing the dense variant!

**Comment by moog16** [comment]
If you need help implementing this please comment on this thread for help :)

**Comment by lucasecdb** [comment]
@moog16 do you know if anyone is working on this? if not, can I?

**Comment by moog16** [comment]
don't think so but would love the help!

**Comment by lucasecdb** [comment]
I've submitted the PR! I'd appreciate if you could review me when you have the time :-)
