### ISSUE TITLE
Controlled TextField with required enabled initially renders invalid

### ISSUE THREAD

**Issue by rjdestigter** [material-components/material-components-web-react#217]
Same issue as `rmwc/TextField` is having: https://github.com/jamesmfriedman/rmwc/issues/280

> If you have a controlled TextField with required set it will initially render as invalid ~due to the initial syncing of the React component props to the MDC component internal state.~ However, required fields should not render as invalid until they lose focus or the form is submitted.

Example: https://codesandbox.io/s/nnjqnqk1yl

**Comment by moog16** [comment]
Ya looks like it is getting the --invalid class on load. Will keep this issue open for tracking

**Comment by moog16** [comment]
Notes for future fixer: 

I think the issue is coming from within the Input.js component:  

```
if (this.props[attr] !== nextProps[attr]) {
        foundation.handleValidationAttributeChange([attributeName]);
        return true;
      }```

The if statement might be assuming something incorrect.
