### ISSUE TITLE
Can only hide label using fullWidth mode

### ISSUE THREAD

**Issue by oste** [material-components/material-components-web-react#224]
When using the TextField component it is only possible to hide the label using `fullWidth` option seen here https://github.com/material-components/material-components-web-react/blob/master/packages/text-field/index.js#L245

I propose that that the label should not be tied to this property and be independent on a new property such as `hideLabel`.

There is a full width example seen here https://material-components.github.io/material-components-web-catalog/#/component/text-field but it seems to just add a `width: 100%` to the `.mdc-text-field--fullwidth` class and not control the floating label. 

I think allowing the floating label to be toggled is definitely useful when using just a `placeholder` works best.

**Comment by moog16** [comment]
label is no longer required as of v0.12.0. This shouldn't be an issue anylonger
