### ISSUE TITLE
Missing ripple on card

### ISSUE THREAD

**Issue by jcburnette** [material-components/material-components-web-react#248]
Hello,

I'm experiencing a problem and I'm not sure if it's something I'm doing wrong or not. I'm using the card component (0.4.2) in a project generated by create react app. When I click on the card, I see the background fade it but the animation for the ripple itself does not appear to fire.

Here is a gif of the behavior I'm seeing:

https://imgur.com/a/3qQkhcW

As you can see, the ripple does not behave in the expected way. As a side note, I have created a clean react application and installed both 0.4.2 and 0.4.1 and both experience this behavior. I have also tried wrapping an element using ripple and it does not work either. The card in rmwc works, however.

Am I doing something wrong or is this a bug in the package?

**Comment by moog16** [comment]
@jcburnette We're missing ripple on the card, and this is a bug. We have a React ripple HOC. You should be able to use that in the meantime until we fix this. We'll get on this bug, but if you figure it out before we fix it, please feel free to open a PR.

Thanks for reporting!

**Comment by bmihelac** [comment]
If I understand correctly, [CardPrimaryContent](https://github.com/material-components/material-components-web-react/blob/master/packages/card/PrimaryContent.js) should be decorated with `withRipple`. For consistency with `MaterialIcon` component, new prop `hasRipple` should be added to `CardPrimaryContent` to be able to have both variant with and without ripple.

**Comment by moog16** [comment]
@bmihelac that's right, the CardPrimaryContent is the only component we provide in Card that should have the ripple on it. Buttons and icons should too, but the end developer is responsible for using the MDCButton or MaterialIcon to attach the ripple to each individual button or icon.

**Comment by moog16** [comment]
are you gonna fix this one too? :)

**Comment by bmihelac** [comment]
sure, I'll try

**Comment by moog16** [comment]
sweet thanks!

**Comment by moog16** [comment]
sweet thanks! If you need help please reach out - let me know if you wanna chat too. I can screenshare or hop onto discord as well. If you think the withRipple HOC can be improved, I'm definitely open to hearing that too.

**Comment by bmihelac** [comment]
sure, will let you know here or on discourse

**Comment by moog16** [comment]
fixed in https://github.com/material-components/material-components-web-react/pull/255
