### ISSUE TITLE
Switch PropType.String --> PropType.node

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#253]
PropType.String is a little restrictive. Some examples where we would want to allow for PropType.node:

```
<Foo text={<Theme {...}>Hello</Theme>} />
<Foo text={<I18n key='something' />} />
<Foo text={<FormatedNumber value={123} /> />
```

This specific issue is concerning Top App Bar. The feature request is being able to put an image into the Top App Bar’s title. The developer specifically referenced the Fortnightly Material study.

**Comment by moog16** [comment]
@bmihelac is there a font-family for the Fortnightly study?

**Comment by bmihelac** [comment]
I cannot find one, but from description I guess it is to expect that logo is image:

> Fortnightly’s top app bar contains a navigation icon, logo, search capability, and chips. The chips present trending hashtags.

**Comment by moog16** [comment]
I'm going to ask the designers, just wondering if you had found anything.

**Comment by bmihelac** [comment]
Even material.io has an image :)

![screen shot 2018-08-30 at 20 10 39](https://user-images.githubusercontent.com/13813/44870615-f75aef00-ac90-11e8-8fc9-138d1b578616.png)

**Comment by sashless** [comment]
The Input Label for MDCTextField is also requiring `text`. Would be nice to allow `PropType.node` as well there.
