### ISSUE TITLE
React Text Field mobile agent problem

### ISSUE THREAD

**Issue by cheong12001** [material-components/material-components-web-react#286]
i have implement this component in my website. However, when i switch the user agent to mobile, and try to touch it. the whole website hangs and shows: "Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops" please help!

**Comment by moog16** [comment]
#275 fixed
