### ISSUE TITLE
chips ripple doesn't extend to the end of the text

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#301]
Steps to repro:

1. click on filter chip with no leading icon

result: notice when the checkmark animates in, the ripple doesn't extend to the end of the chip

**Comment by TroyTae** [comment]
Can I ask you more detail about this issue?
I installed "@material/react-chips": "^0.10.0", but it looks to work well.

**Comment by moog16** [comment]
@TroyTae - this bug is specifically regarding FilterChips without a leading icon. The ripple isn't calculated correctly since there is no leading icon, and when the filter chip animates in, it still thinks its the shorter length.

**Comment by TroyTae** [comment]
Is there some bug replay code?
I test like this:
https://drive.google.com/open?id=17OgCyy24BA9j16utns3pADIx7Dird9Z9

**Comment by moog16** [comment]
I actually don't think you have the ripple on there. Although I the video might be missing some frames. Can you confirm this?

**Comment by TroyTae** [comment]
https://material-components.github.io/material-components-web-catalog/#/component/chips
Does MCW has same issue?
I can see that Ripple is appied my video and MCW example.
But when no leading icon Filter Chips, but ripple doesn't spread from clicked point.

**Comment by moog16** [comment]
Actually it looks like the chips catalog page isn't working. I think this is an existing bug. 

Regarding the filter input chips it looks like the ripple isn't completely working in the React screenshot tests. So this is still most likely a bug.

<img width="313" alt="Screen Shot 2019-03-18 at 11 55 46 AM" src="https://user-images.githubusercontent.com/579873/54555904-efd10e00-4974-11e9-8e6c-978e330e215d.png">

**Comment by TroyTae** [comment]
![스크린샷 2019-03-19 오후 8 05 27](https://user-images.githubusercontent.com/20078201/54601862-76741100-4a83-11e9-907c-e065267a4f14.png)
I cannot sure that our thought same.
I think material-components-web-react and material-components-web had same issue.
That is chip's ripple can't calculate clicked point and style variable "translate-start" has NaN.
Is your idea the same?

**Comment by moog16** [comment]
Ah you're correct - I thought that was working yesterday when I checked. That specific issue must be a MDC Web issue then. We cannot confirm if the chips ripple extends to the end of the text bug is fixed without fixing this bug first. 

I confirmed this with this [codepen](https://codepen.io/moog16/pen/MxqbRY).

**Comment by moog16** [comment]
@TroyTae looks like there is already an MDC Web issue for it: https://github.com/material-components/material-components-web/issues/2812

**Comment by TroyTae** [comment]
@moog16 
Fixed on https://github.com/material-components/material-components-web/pull/4565

**Comment by moog16** [comment]
Cool! Looks like its in [v1.1.1](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#111-2019-04-08). Let's update chips to v1.1.1 in the feat/mdcweb-typescript-update branch.

**Comment by moog16** [comment]
Closing for #804
