### ISSUE TITLE
@material/react-menu-surface is not published

### ISSUE THREAD

**Issue by bguillou** [material-components/material-components-web-react#334]
When I try to install `@material/react-menu-surface` I get a 404 error.

<img width="586" alt="material react-menu-surface" src="https://user-images.githubusercontent.com/9253663/46960396-ba12bb00-d09e-11e8-9584-817b396fa44c.png">

The component has not been published yet

**Comment by moog16** [comment]
@bguillou we aren't actually publishing menu-surface until next week tuesday.

**Comment by moog16** [comment]
Has been published!
