### ISSUE TITLE
TabBar - Does not render horizontally like Tabs

### ISSUE THREAD

**Issue by zulucoda** [material-components/material-components-web-react#344]
**Reproduced in this repo:** https://github.com/zulucoda/test-react-material-components

**Issue:**
The `TabBar` component currently renders Tabs vertically.

**Expected:**
The `TabBar` component should render Tabs horizontally.

**Example:** 
https://material.io/design/components/tabs.html#

**Current Issue Image:**
<img width="142" alt="screen shot 2018-10-15 at 6 56 54 pm" src="https://user-images.githubusercontent.com/994819/47065895-8c8c5580-d1f5-11e8-98e6-fe9890c14091.png">

**Comment by moog16** [comment]
@zulucoda You also need to include the tab-scroller styles in your app. We failed to mention this in the readme, so we'll require that change. But to fix your issue, you can add the following line to the top of your App.js file.

```
import '@material/react-tab-scroller/dist/tab-scroller.css';```

**Comment by moog16** [comment]
@zulucoda opened readme fix! Thanks for opening the issue.

**Comment by zulucoda** [comment]
@moog16 thanks buddy for the fix.
