### ISSUE TITLE
Support checkboxes in list

### ISSUE THREAD

**Issue by bonniezhou** [material-components/material-components-web-react#352]
Implement `ListItem.toggleCheckbox`

**Comment by moog16** [comment]
toggleCheckbox is no longer an adapter method, but has been replaced by 3 other adapters: https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#0420-2018-12-04

**Comment by moog16** [comment]
Deprecated feature. Now tracked in https://github.com/material-components/material-components-web-react/issues/438
