### ISSUE TITLE
[drawer] Change from modal and non-modal at runtime

### ISSUE THREAD

**Issue by lucasecdb** [material-components/material-components-web-react#408]
hello guys! :-)

## Description

I'm using the `Drawer` component and I wanted it to change between modal and fixed version and vice-versa depending on the `window.innerWidth`, but the component crashes when it goes from `modal={false}` to `modal={true}` and I try to open it.

Bellow is the link to the codesandbox with the behaviour I've encountered.

## Reproduction sandbox

[![Edit 6wm7myn9yk](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6wm7myn9yk)

**Comment by moog16** [comment]
@lucasecdb thanks for reporting this issue. Totally a use case we need to support. The issue is permanent does not initialize a foundation. I'll fix the issue with 7.0
