### ISSUE TITLE
Ripple doesn't trigger on key down event

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#41]
Steps to reproduce:

1. Start screenshot tests
1. Go to button screenshots
1. Bring to focus a button using the keyboard
1. While focused on a button, press space bar or enter key

Actual Results:
No Ripple is activated

Expected Results:
Ripple should activate, similar to MDC Web

**Comment by bonniezhou** [comment]
It's also missing visual feedback for focus/blur.
