### ISSUE TITLE
react-tab-indicator package missing index.js

### ISSUE THREAD

**Issue by pladaria** [material-components/material-components-web-react#410]
Looks like there's a problem with this package

https://unpkg.com/@material/react-tab-indicator@0.6.0/dist/index.js

**Comment by moog16** [comment]
Thanks for reporting this. Our latest release had a few bugs, but we're patching a fix today! Please look out for it.

**Comment by moog16** [comment]
Please try https://unpkg.com/@material/react-tab-indicator@0.6.2/dist/index.js
