### ISSUE TITLE
New component implementation: Linear progress

### ISSUE THREAD

**Issue by hvolschenk** [material-components/material-components-web-react#411]
Hiya,

I'd like to add a linear progress component implementation. I am comfortable with the component and adapter creation.

The part I am unsure about though is how to add a _golden_ screenshot for this. The dots move at a rather rapid pace and I am scared they don't line up properly for subsequent screenshots because of timing issues.

Edit: this might also be an issue for the `indeterminate` variant.

Any advice for how to proceed with screenshots for this component?

**Comment by moog16** [comment]
@hvolschenk you're going to use the foundation/adapter from mdc web to build the linear progress component? 

We actually don't keep track of any of the browser events. You already have it running on docker, correct? We use [puppeteer](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md), and I'm sure they have something in there that can help us. I think we can update the screenshots in a separate PR, and then the linear progress changes can absorb those. How does that sound?

**Comment by hvolschenk** [comment]
Hiya,

Yeah I'll be building the adapter using the given foundation, taking example from some other [existing implementations](https://github.com/material-components/material-components-web-react/blob/master/packages/switch/index.js#L72).

As for the screenshots, what I mean is:
The linear progress component has an animated background, as can be seen in [the demo](https://material-components.github.io/material-components-web-catalog/#/component/linear-progress-indicator). The screenshots are taken from that page, I was/am just afraid that the moving dots (that make up the "un-progressed" piece) won't line up each time a screenshot is taken.

My thinking is that there might be a millisecond or two delay before the screenshot is taken with puppeteer in which time the dots would/could have moved, thus making the screenshots unreliable. Or am I incorrect in thinking this?

**Comment by moog16** [comment]
No I think you're correct. I think we should try doing the buffered and indeterminate variants, but as you can see on the demo page https://material-components.github.io/material-components-web-catalog/#/component/linear-progress-indicator, there are stationary variants. So worse comes to worse we can just use those.

**Comment by hvolschenk** [comment]
@moog16 Can I close this issue now that #425 is merged?

**Comment by moog16** [comment]
Closing!
