### ISSUE TITLE
Upgrade MDC Web to ^0.35.0

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#42]
Currently all packages are on 0.34.1, but should be using latest (v0.35.0).

Known issues:
Ripple is broken, and needs to wrap the `foundation.activate()` call in a `requestAnimationFrame`. Not sure why this is the case, so further investigation is needed.

**Comment by bonniezhou** [comment]
We should also make a changelog.

**Comment by moog16** [comment]
Good call! Opened a new issue: https://github.com/material-components/material-components-web-react/issues/56
