### ISSUE TITLE
Add Snackbar component

### ISSUE THREAD

**Issue by zemirco** [material-components/material-components-web-react#447]
Hey,

first of all: Thank you! Thank you for providing the Components and the React Wrapper. At the beginning there was only the Material Design Styleguide. No real code. Therefore we build our own implementation https://github.com/HBM/md-components. For our latest product we started using your components because we really like the quality. You're doing a great job.

A snackbar is pretty important to us. We need it for confirming user actions. It already exists for the web https://github.com/material-components/material-components-web/tree/master/packages/mdc-snackbar. Any plans on adding it to the React wrapper?

Best regards,
Mirco

**Comment by moog16** [comment]
@zemirco This will be in our TODO for the new year. Currently snackbar is being rebuilt in MDC Web. Please see [branch](https://github.com/material-components/material-components-web/tree/feat/snackbar).

**Comment by beaumartinez** [comment]
Snackbar is now [in master](https://github.com/material-components/material-components-web/tree/cffe8951ff8827b6107af2b4d0582110a95ec9a5/packages/mdc-snackbar) for MDC web. Any update on moving forward with a React component for it?

**Comment by moog16** [comment]
We're actually in a holding pattern as most of the MDC React team is implementing typescript in MDC Web. Until that is complete we won't be building any new components (we estimate through February). If you would like to take a stab at implementing (or anyone else) please feel free. We will be doing monthly releases. See https://github.com/material-components/material-components-web-react/pull/611 for some inspiration ;)

**Comment by beaumartinez** [comment]
Thanks @moog16. I see @gugu (and yourself) are already working on it in #620.

**Comment by moog16** [comment]
@beaumartinez ya you're totally right. My mind just blanked on that whole PR. Thanks :)

**Comment by moog16** [comment]
fixed with #620
