### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by rflmyk** [material-components/material-components-web-react#45]
When I try import like example:
```
import LineRipple from '@material/react-line-ripple';
```
And try use:

```
class Foo extends Components {
    render() {
        return(
            <div>
                <LineRipple />
                ...
            </div>
        )
    }
}
```

Then throw:

```
ERROR in ./node_modules/@material/react-line-ripple/index.js
Module parse failed: Unexpected token (8:14)
You may need an appropriate loader to handle this file type.
| export default class LineRipple extends Component {
|
|   foundation_ = null;
|
|   state = {
...
```

Someone has a proposal solution for that?
Thank's guys ;)

**Comment by ch4nd4n** [comment]
+1 
I tried out with [create-react-app](https://github.com/facebook/create-react-app) and it fails with following response.

Failed to compile.

```shell
./node_modules/@material/react-button/index.js
Module parse failed: Unexpected token (17:6)
You may need an appropriate loader to handle this file type.
|       initRipple,
|       unbounded, // eslint-disable-line no-unused-vars
|       ...otherProps
|     } = this.props;
|
```

package.json

```JSON
{
  "name": "chandan",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material/react-button": "^0.1.0",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```
App.js
```JavaScript
import React, { Component } from 'react';

import Button from '@material/react-button';

class App extends Component {
  render() {
    return (
      <div className="App">
          <Button>
            Click Me!
          </Button>
      </div>
    );
  }
}

export default App;
```

**Comment by mikefresh** [comment]
Hey hey. The packages are not compiled down to es5 so they choke when trying to use them. They have an issue open for it #5. You can use Babel to crosscompile them yourselves. You will need the Jsx and spread plugins to do it!

**Comment by rflmyk** [comment]
Yep, We are using jsx with webpack, but even so dont compile

**Comment by mikefresh** [comment]
I’m so very new to this so I hope it’s good information but, with cra unless you eject then it’s using their default webpackconfig which will ignore modules ja?

To test yesterday I downloaded the repo and used the cli to convert locally, that worked.

**Comment by rflmyk** [comment]
Interessanting, but I try include and dont work, I will try atnight, thanks.

**Comment by mikefresh** [comment]
Example: This will just do one file, you can of course create a config file and run them yourselves or eject (which is one way) and then setup webpack to pull it out of your modules. The below worked for me just to test out some of the components. 
 
`babel ActionButtons.js --plugins=transform-object-rest-spread,babel-plugin-transform-react-jsx,babel-plugin-transform-class-properties`

**Comment by moog16** [comment]
Yup, as @mikefresh [mentioned](https://github.com/material-components/material-components-web-react/issues/45#issuecomment-388365916) this is because we haven't transpiled down to ES5 from ES6. `create-react-app` doesn't make it easy to make edits to the webpack config (since you have to eject). We're working on PR #46 to solve this issue. 

Once merged you'll be able to import ES5 like so:

```js
import LineRipple from '@material/react-line-ripple/dist';
```

Docs are updated in this file in the PR: https://github.com/material-components/material-components-web-react/pull/46/files#diff-489fb3d3b95aa8382eddcef4fb7ad586

**Comment by guix77** [comment]
https://github.com/material-components/material-components-web-react/pull/46 just merged, great ! Any chance for a new release compatible with React, soon ?

**Comment by moog16** [comment]
MDC-Web is scheduled to release on Monday. I will be attempting a sync
then. After syncing is when you can expect it to be released. I'm not sure
how easy/difficult this will be since it is the first sync, but I believe
it will be done before end of next week.

**Comment by devxpy** [comment]
Why not ship these on npm, why require the user to build ?

**Comment by ayozebarrera** [comment]
Importing /dist not working for me

**Comment by BrunoQuaresma** [comment]
Any updates?

**Comment by moog16** [comment]
@BrunoQuaresma its live! v0.2.0 on npm

**Comment by devxpy** [comment]
Dope!
