### ISSUE TITLE
List expand collapse

### ISSUE THREAD

**Issue by windgaucho** [material-components/material-components-web-react#461]
Hi,

There is any way to use the expand collapse as showed here?
[https://material.io/design/components/lists.html#types](url)

![image](https://user-images.githubusercontent.com/8983953/48816619-a7d11000-ed21-11e8-920c-c7e550092328.png)

Thanks.

**Comment by moog16** [comment]
@windgaucho MDC Web does not have this feature currently supported. Unfortunately we cannot help with that.

I would suggest using our List component and adding the animations manually. If you have a codepen, maybe we can work together on achieving the desired effect.

**Comment by moog16** [comment]
Going to close issue, but please ping me here with code snippet if you decide to go that route.

**Comment by vzaidman** [comment]
@moog16 would you like a contribution of the expand functionality? do you know if it's in any road map / being worked on?

**Comment by moog16** [comment]
@vzaidman this is not on the roadmap of web, which means we can't support it on MDC React. If you would like to see this, I'd suggest opening an issue there. I did a search for all open issues and didn't find that open.

**Comment by anatolibarski** [comment]
I've been selecting a ui framework and one of the main reasons was this extremely useful expand/collapse functionality. To find out later, that you are not planning to implement the spec...
Any reason why it is not on the roadmap?
