### ISSUE TITLE
ListDivider and list-style-type

### ISSUE THREAD

**Issue by windgaucho** [material-components/material-components-web-react#469]
Hi,

I am using ListDivider and when it render it has the list point:

![image](https://user-images.githubusercontent.com/8983953/48877133-9a2e8f80-ede0-11e8-94f0-f3d86901b97b.png)

It is by design?

I must to use style={{ 'list-style-type': 'none' }} in ListDivider, for the point to disappear.

**Comment by moog16** [comment]
@windgaucho can you please copy/paste what your styles are here? Are you using Sass or CSS?

**Comment by windgaucho** [comment]
@moog16
Just intalled list component:

[https://github.com/material-components/material-components-web-react/tree/master/packages/list#installation](url)

I am using sass, so I imported the sass file:
[https://github.com/material-components/material-components-web-react/tree/master/packages/list#styles](url)

 just copy this example:
[https://github.com/material-components/material-components-web-react/tree/master/packages/list#list-groups-and-list-dividers](url)

and modified it with my own text.

**Comment by windgaucho** [comment]
Here is my final code with of the drawer render with the styles applied:

````
    <ListGroup>
      <ListGroupSubheader tag="h2">
        <div style={style.divListGroupHeader}>
          <MaterialIcon icon="settings" style={style.iconListGroupHeader} />Folders
        </div>
      </ListGroupSubheader>
      <List singleSelection>
        <Link to="/photos" style={style.link}>
          <ListItem style={style.listItems}><ListItemText primaryText="Photos" /></ListItem>
        </Link>
      </List>
      <ListDivider style={{ listStyleType: 'none' }} />
      <ListGroupSubheader tag="h2">
        <div style={style.divListGroupHeader}>
          <MaterialIcon icon="equalizer" style={style.iconListGroupHeader} />Recent Files
        </div>
      </ListGroupSubheader>
      <List>
        <Link to="/administracion/clientes" style={style.link}>
          <ListItem style={style.listItems}><ListItemText primaryText="Vacation" /></ListItem>
        </Link>
    </ListGroup>
````
the styles:
````
const style = {
  divListGroupHeader: {
    display: 'inline-flex',
    alignItems: 'center',
  },
  iconListGroupHeader: {
    paddingRight: 10,
  },
  listItems: {
    paddingLeft: 40,
  },
  link: {
    textDecoration: 'none',
  },
};
````

**Comment by moog16** [comment]
@windgaucho did you get a chance to see my comment from https://github.com/material-components/material-components-web-react/issues/470?

**Comment by moog16** [comment]
closing as its a dup of #470
