### ISSUE TITLE
usage ListItem with react router

### ISSUE THREAD

**Issue by windgaucho** [material-components/material-components-web-react#470]
Hi,

Currently I have the following code:

```
     <List singleSelection selectedIndex={0}>
        <Link to="/route1" style={style.link}>
          <ListItem style={style.listItems}><ListItemText primaryText="Route 1" /></ListItem>
        </Link>
        <Link to="/route2" style={style.link}>
          <ListItem style={style.listItems}><ListItemText primaryText="Route 2" /></ListItem>
        </Link>
      </List>
```
And the navigation works ok, but I loose the scss design of the selected list item (mdc-list-item--activated is not applied to the selected item), I supose it is because the Link of react-router-dom render an `a` anchor before the `li` element.
How can I user the Link of react router without loose the design scss element ?

**Comment by windgaucho** [comment]
Yes, I am already doing like that.
You are using the the onClick method of the ListItem, so what is the Link for?

**Comment by moog16** [comment]
Great is that working for you? Link can be used interchangeably with the `push` method. Link is a shortcut for 

```<a onClick={this.onClick}>...```

**Comment by moog16** [comment]
Closing as this issue has gone stale
