### ISSUE TITLE
bug(text-field): destroying foundation fails

### ISSUE THREAD

**Issue by hvolschenk** [material-components/material-components-web-react#489]
Hiya,

This is a bit of a tricky one to describe so please bear with me for a moment.

I have a `react-redux` container which connects a form to a store. On mount a fetch is fired off to get a list of countries to display in a `@material/react-select`. The form itself is part of a render-prop so it only gets rendered when the list of countries is fetched successfully.

When rendering the component for the first time the state goes from _Pending_ to _Success_ and thus swaps out a loader for the actual form. All good so far.

When I navigate to another route and hit the back button in my browser, the state is still _Success_ so the form starts rendering immediately. The mount fetch method fires off which then immediately swaps the status to _Pending_ again. It is at this point where `@material/react-text-field` breaks.

As the swapping between statuses happens so fast the `@material/react-text-field` never actually gets mounted before un-mounting again. When it un-mounts `this.foundation_.destroy()` gets called but at that point `this.foundation_` is still set to `null`, thus throwing the classic `Cannot read property 'destroy' of null` error.

**Possible solutions**:

I could change the status of the countries list to _Pending_ or something similar myself the moment the form un-mounts. This doesn't sound right though.

! could check if the countries list is already fetched on mount and then not fetch it again on the second mount. This works but not quite what I'd prefer as this same problem could be seen for lists that I actually _do_ want updated every time to prevent stale data.

I could add a check to the `@material/react-text-field`'s `componentWillUnmount` method to only destroy the foundation if it already exists. I would prefer this, but would have to do this for all form controls as the same could happen on selects, checkboxes etc.

Please let me know what you think.

**Comment by moog16** [comment]
I'm thinking a few things:

1. Why do you need to re-fetch countries if they are already populated? I would think a list of countries do not need to change often. 
1. I think others will also run into this issue.

So the text-field is not mounting before unmounting? I don't think there is anything asynchronous about the unmounting text-field lifecycle?

IDEA: What if we don't render the text-field until this.foundation is set? Would that fix this issue? What I don't understand is the `componentDidMount` not completing before `componentWillUnmount` starts.

**Comment by hvolschenk** [comment]
Yeah I agree.

1. The country-list thing might be a bit over-simplified, and I should definitely cache results like that one. It could be a problem with other types of data though.
2. At some point, probably.

Yeah the field does not mount before unmounting. The fetch is cached, thus returns data in a few milliseconds, thus the `componentDidMount` never fires, although the component has started it's process. Because of this the `foundation` never exists to be able to `.destroy()` it.

I was thinking to just make sure the foundation exists before trying to destroy it, something like:

```js
componentWillUnmount() {
  if (this.foundation) {
    this.foundation.destroy();
  }
}
```

**Comment by moog16** [comment]
That makes sense. We could also introduce a `mounted_` flag, which we set true in componentDidMount. Either way makes sense. Will you open a PR? :)

**Comment by hvolschenk** [comment]
Yup. I can do that. Will see if I get a chance tonight. Which option do you prefer?

My initial thought is to check for `this.foundation` for the off chance it doesn't exist for some other reason, but that might be considered _overly defensive programming_.

**Comment by moog16** [comment]
Ya that makes sense to me! I'm currently doing a typescript conversion, which you can follow in the branch `feat/typescript`. So this change might happen anyways.

BTW you're the best! Thanks so much
