### ISSUE TITLE
Add children to Top app bar

### ISSUE THREAD

**Issue by jfily** [material-components/material-components-web-react#499]
Hi,

We should be able to add children to top app bar component.
I want to add some tabs in another mdc-top-app-bar__row.

**Comment by moog16** [comment]
Is this an example of what you're trying to do https://adopt-a-pup.glitch.me/? This is in web, but the React component should allow this too.

**Comment by jfily** [comment]
This is exactly what I want to do.

**Comment by moog16** [comment]
@jfily I've been meaning to get back to Top App Bar to make it more flexible. It was one of the first components we built, which we've since learned a lot. This is definitely one of the features we should build into it. Currently we are converting to typescript, which makes it difficult to fit this bug in before the end of the year. Sorry if this blocks you, but I think it would be faster if you fork and make updates. Does that work?

Thanks for opening!

**Comment by jfily** [comment]
@moog16 Hum, I can but I'm kinda new to React. It's not blocking me, I'm learning React by migrating a little app I've made.
What do you prefer, using a "tabs" prop like for actions or rendering children ?
After a quick look at Material specs, a 2nd row can be used only for tabs so... I personally prefer the tabs property cause only one row is recommanded (nested tabs ain't "forbidden" but need to be used with caution)

Specs : https://material.io/design/components/tabs.html#fixed-tabs

**Comment by moog16** [comment]
Actually on second thought, if you want the tabs to always be visible, you may be able to just instantiate <TabBar>... right below the <TopAppBar>. 

RE tabs props vs children: I prefer children, but it could be difficult since there are many items in the top app bar (title, actionitems, etc). Given that we want to keep order for the child elements, it may be easier to use `children`.

**Comment by mgr34** [comment]
I also have need for a `top-app-bar` to have children. Similar to the new google webmaster tools I would like to be able to place an input between my title and actionItems. My preference would be for separate components such as `<TopAppBarSection/>` <TopAppBarRow/>` Not unlike how `<List>` has `<ListItem>` `<ListItemText>`.

**Comment by moog16** [comment]
@mgr34 You're saying you'd like it to be more compositional? 

Also what webmaster tools are you talking about?

**Comment by mgr34** [comment]
@moog16 

>You're saying you'd like it to be more compositional?

I believe that would be a solution. Because if you just allow `<TopAppBar>` to render children the question becomes where? 

> Also What webmaster tools are you talking about

Sorry, should've posted the link: http://search.google.com/search-console

**Comment by moog16** [comment]
yup that makes sense. I'll have to run this by the team, but I do prefer composition.

**Comment by moog16** [comment]
@mgr34 I ran this by the team, and we want to move towards a compositional/declarative syntax where you would build up your top app bar (similar to list like you said in an above comment). I have opened a top app bar web issue (#4175).

**Comment by ItsLeeOwen** [comment]
Does this issue cover the use case where you'd like to use an element instead of string for TopAppBar `title`?

**Comment by mgr34** [comment]
@moog16, I'd like to work on this issue in the near future. Might you have any specs outside of a more declarative syntax? 

Before diving into it, I would imagine this would slim down  `<TopAppBar/>` (index.tsx) and introduce a slew of breaking changes. the TopAppBarProps interface would see `actionItems` , `navigationIcon`, and `title` moved `<TopAppBarSection/>`.  Additionally, Section would see new `align` prop introduced. '<TopAppBar/>' simply render its children. I don't see a point in restricting its children, however, it would be recommended that the first child be `<TopAppBarRow/>`. All components should simply render children. 

Would it also be okay to upgrade the component to mdc-web 0.43.1? I could see where a separate PR might make sense; however, this seems like a "rewrite" and perhaps fair to consider? If I am reading the CHANGELONG correctly there have not been any new breaking changes, and one bug fix in 0.42.0.

**Comment by moog16** [comment]
@mgr34 Yes I have some ideas...similar to how there is a FixedAdjust, there should also be components we provide for the actionIcons/navigationIcons and title. Also as you mentioned we need to wrap these in a TopAppBarSection.

Only requirements is that we maintain the MDC Web's feature set and use all the foundation methods/implement all of the adapter methods. There are some cases where it does not make sense, but we'll need to discuss each one.

And I believe you're right - there hasn't been any new features, thus no breaking changes. So updating should be fine.
