### ISSUE TITLE
Menu surface are not removed from DOM on unmount

### ISSUE THREAD

**Issue by jfily** [material-components/material-components-web-react#500]
Hi,

On mount, MenuSurface components are moved to \<body\> but are not removed from DOM on unmount.

**Comment by moog16** [comment]
This is actually a duplicate of this: https://github.com/material-components/material-components-web-react/issues/455. Your issue is actually more accurate. I will close #455.

Also marking this help wanted if you'd like to open a PR.

**Comment by moog16** [comment]
Closed with #693
