### ISSUE TITLE
[CardMedia] The imageUrl prop does not load the picture or media.

### ISSUE THREAD

**Issue by CodyCline** [material-components/material-components-web-react#503]
Passing a URL or directory path to the `imageUrl` prop of the `<CardMedia>` component won't display the image, period. The workaround is just to use a standard `<img>` tag which loads nicely into the `<Card>` component.
Example Code: 
```
import Card, {CardPrimaryContent, CardMedia} from '@material/react-card';

<Card>
    <CardPrimaryContent>
        <CardMedia imageUrl='http://via.placeholder.com/350x150'>
            <span>Fancy Image</span>
        </CardMedia>
    </CardPrimaryContent>
</Card>
```
Expected Result: Image won't load; but the `<span>` tag will display.
Troubleshooting ideas I've tried which haven't worked: 
- Used a `src` or `href` in place of the `imageUrl` prop
- Loaded an image from either a local folder directory and a online URL
- Reinstalled the npm package 

Is there something i'm missing? Help much appreciated! 😃

**Comment by moog16** [comment]
@CodyCline thanks for opening this issue. I think this is actually an issue with our documentation. CardMedia requires that you have an aspect ratio of either `square` or `wide`. Please see below:

```js
import React, { Component } from 'react';
import './App.scss';
import '@material/react-card/index.scss';
import '@material/react-button/index.scss';
import '@material/react-material-icon/index.scss';

import Card, {
  CardPrimaryContent,
  CardMedia,
  CardActions,
  CardActionButtons,
  CardActionIcons
} from "@material/react-card";
import Button from '@material/react-button';
import MaterialIcon from '@material/react-material-icon'; // also need to add the <link> tag in the index.html file

class App extends Component {
  render() {
    return (
      <div style={{padding: '24px'}}>
        <Card style={{width: '250px'}}>
          <CardPrimaryContent>
            <h1>Header</h1>
            <CardMedia square imageUrl='https://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg' />
          </CardPrimaryContent>

          <CardActions>
            <CardActionButtons>
              <Button>Click Me</Button>
            </CardActionButtons>
            <CardActionIcons>
              <MaterialIcon icon='favorite' />
            </CardActionIcons>
          </CardActions>
        </Card>
      </div>
    );
  }
}

export default App;
```
If you do not like the square or wide props, you can create your own class using this [Sass mixin](https://github.com/material-components/material-components-web/blob/master/packages/mdc-card/_mixins.scss#L43).

I will keep this open to update Readme so that others do not run into this issue.

**Comment by CodyCline** [comment]
Thank you, @moog16 that makes a lot of sense now. You were very helpful!

**Comment by moog16** [comment]
Closed w/ #504

**Comment by samuelnihoul** [comment]
It still doesn't work by me :( imageUrl and square are not recognized as valid attributes.

**Comment by mendrikaRalison** [comment]
add prop component="img"
