### ISSUE TITLE
Upgrade npm version from 0.0.10 to last release 1.0.0

### ISSUE THREAD

**Issue by totaki** [material-components/material-components-web-react#51]
https://www.npmjs.com/package/material-components-web-react
in npm packages you very old release, please fix it

**Comment by mikefresh** [comment]
Totaki that thing on NMP is not this repo. I think. -> (https://github.com/MihirNS/material-components-web-react)

**Comment by totaki** [comment]
I find this one https://github.com/jamesmfriedman/rmwc, thank you

**Comment by kfranqueiro** [comment]
Sorry for the confusion this has caused. We currently don't have an all-in-one package for MDC React, and I didn't realize that `material-components-web-react` already existed and is owned by someone else. I'll make sure to discuss this confusion with our team.

The first-party MDC React components can generally be found at `@material/react-<component-name>`. So, for example, while `@material/button` is the vanilla MDC Web Button implementation, `@material/react-button` is the MDC React Button implementation.

RMWC is a third-party set of React wrappers for MDC Web by James Friedman, who has done a great deal of amazing work maintaining it!
