### ISSUE TITLE
bug(top-app-bar): foundation should be destroyed and reinitialized on variant change

### ISSUE THREAD

**Issue by mgr34** [material-components/material-components-web-react#517]
When the  `<TopAppBar/>`'s variant changes the foundation is not reinitialized. For example,  if  mounted with `fixed=true` and an update changes this to  `fixed=false`  the component should `destroy()` the present  foundation (an instanceof `MDCFixedTopAppBarFoundation`) and reinitialize a plain `MDCTopAppBarFoundation`. Otherwise upon scroll `mdc-top-app-bar--fixed-scrolled ` className will be added to the `<TopAppBar/>`. 

> Note: I believe I have a PR nearly complete. New to Screenshot testing. Had some issues figuring out setting up the environment (see: discord ).

**Comment by moog16** [comment]
@mgr34 Ya we do need something to switch if that is your intention. This is similar to the Drawer. Please see this https://github.com/material-components/material-components-web-react/commit/36e6316c9f322ee88f9f580decf72a8b7d11d9c7. 

I think the same principles can be applied to top app bar.
