### ISSUE TITLE
feat(top-app-bar): is missing dense variant

### ISSUE THREAD

**Issue by mgr34** [material-components/material-components-web-react#518]
The `<TopAppBar />` should contain a [dense variant](https://github.com/material-components/material-components-web/blob/master/packages/mdc-top-app-bar/README.md#dense]) [[0](https://github.com/material-components/material-components-web/blob/master/packages/mdc-top-app-bar/README.md#dense)]. 

Should a fix for this also include a dense (and prominent) props for the `<TopAppBarFixedAdjust/>` component (and should I open an additional issue?)

I think I could have a PR for this later today.

[0] https://github.com/material-components/material-components-web/blob/master/packages/mdc-top-app-bar/README.md#dense

**Comment by moog16** [comment]
That'd be great! 

What do you mean (and prominent). We already have the styles for the prominent class.

**Comment by mgr34** [comment]
I neglected the \`'s when writing `<TopAppBarFixedAdjust/>` which hid it from my comment. At present fixed adjust does not appear to add `mdc-top-app-bar--dense-prominent-fixed-adjust` , `mdc-top-app-bar--prominent-fixed-adjust` , `mdc-top-app-bar--short-fixed-adjust`, or `mdc-top-app-bar--dense-fixed-adjust`

**Comment by moog16** [comment]
ahhh - yes you're totally correct. Can you do 2 separate PRs? You can reference this single issue. :+1:

**Comment by mgr34** [comment]
@moog16  yes I can do 2 PR's. I'll also need to update the documentation/README.md with each PR. Or is the preference for documentation updates to be in a 3rd PR (seems excessive)?

**Comment by moog16** [comment]
Just keep the REadme updates in the same PR as the changes. I just want the PRs to be separate since they are logically different fixes.

**Comment by mgr34** [comment]
As I work on correcting the missing options of the `<TopAppBarFixedAdjust/>` I cannot help but wonder if `<TopAppBar>` is too verbose. In part because a lot of the options need to be repeated for the fixed adjust and type checking. Why not simplify the whole thing and have a `type` property.

Take for example the following

```jsx
    <div className='top-app-bar-container'>
      <TopAppBar  prominent  dense  title='App Title' />
      <TopAppBarFixedAdjust prominent dense >
          <p>blah, blah, blah</p>
       </TopAppBarFixedAdjust>
    </div>     
```

could be rewritten to
```jsx
    <div className='top-app-bar-container'>
      <TopAppBar title='App Title' type='prominentDense'/>
      <TopAppBarFixedAdjust type='prominentDense' >
          <p>blah, blah, blah</p>
       </TopAppBarFixedAdjust>
    </div>     
````


That may not look like anything too significant but consider the following.
  1. there is nothing stopping someone from writing  `<TopAppBar prominent short fixed/>`  A type property could enforce a single type from a constrained list.
  2. this would simplify my recent PR #519 to something 

```jsx
       componentDidUpdate(prevProps) { 
          if (this.props.type !== prevProps.type) {
             this.initializeFoundation() 
           }
      }
````
  3. It is conceivable that a user may want a prominent dense TopAppBar on a desktop, and a fixed variant for a tablet, and a standard variant for mobile. Simplifying it with a single property sure looks attractive.
```jsx
     <div>
        <TopAppBar
           fixed={state.display === 'tablet'} 
           prominent={state.display === 'desktop'} 
           dense={state.display === 'desktop}'
         />
       <TopAppBarFixedAdjust 
            prominent={state.display === 'desktop'} 
            dense={state.display === 'desktop'} 
        />
  </div>
```

  4. Especially when you consider `<TopAppBar>` also has a lot of long properties already with `navigationIcon`, and `actionItems`. 


presuming the adoption of `type` property proves successful the question I have is such a property camelCased? If it were to be delimited with a hyphen it could be useful for class name generation?

```es6
    const BASE_CLASS = 'mdc-top-app-bar';
    const className = `${BASE_CLASS}--${type}`;
 ```

Of course a regex that does a conversion could also be whipped up without issue.

(Sorry this got a bit long winded. Would you prefer I split this off into another issue?)

**Comment by moog16** [comment]
@mgr34 I don't think you would ever have more than 2 different types. Technically prominent, short,and fixed are not supposed to work together (at least it hasn't been tested). We just don't restrict the user from being able to do that. Also by combining the different types into one string, we'd now have to have enums for each combination we do support. I think the way we have it is more extensible. 

I see where you are coming from in your #2, but again there are only 4 or 5 different props we'll need to check.

**Comment by moog16** [comment]
This pattern is littered in the all components (ie button, list, etc). I think it would have to be a system wide change if we were to go down that road. I just don't think that we gain that much from it. I do like the idea of having enums. However we are in the middle of a typescript rewrite, which would complicate things. That change would have to wait until next year. But we can revisit the issue then! Thanks :)

**Comment by moog16** [comment]
#524 merged. Thanks again @mgr34 !
