### ISSUE TITLE
is there MDC react native ?

### ISSUE THREAD

**Issue by geminiyellow** [material-components/material-components-web-react#542]
hi all, i want to use this lib in react-native, but it looks not support.
is there plan in roadmap or never ?

**Comment by moog16** [comment]
No there is currently no plan to do a react-native wrapper for MDC. However there looks to be some clones out there ( from a quick google search) :
- https://github.com/react-native-material-design/react-native-material-design
- https://medium.com/@victorvarghese/super-cool-material-ui-components-in-react-native-dd7c4434bc26

**Comment by geminiyellow** [comment]
@moog16 thank you, i knew there are lots of good material components set, but because MDC is the best material components lib why i create this issues. thank you again.
