### ISSUE TITLE
<Input> does not support access to underlying HTML

### ISSUE THREAD

**Issue by vanillabeach** [material-components/material-components-web-react#544]
_This is my first ever GitHub issue, so let me know if you need more information, or if I have written something incorrectly._

I am using the `<TextField>` component (0.7.1) with React + TypeScript. 

I would like to be able to access the underlying HTML Element for the `<Input>` subcomponent in order to add some trivial UI functionality (such as selecting all the text in the input field on focus).

It would be good to ensure that the underlying Element for the `<Input>` is publicly accessible. For example, placing a **ref** on the parent `<div>` for `<Input>` and providing a public method that would return this (e.g. getHTMLInputElement). Then I could do something like:

```
 <Input onFocus={this.inputRef.getHTMLInputElement().select()} />
```

**ADDITIONAL INFORMATION**

It seems that the **ref** attribute is not working for `<Input>`. For example:

```
class CustomTextField extends React.Component<Props, State> {
  inputRef: React.RefObject<Input>;

  ...

  showRef() {
    console.log("showRef", this.inputRef);
  }

  render() {
    const { className, label, ...otherProps } = this.props;

    return (
      <span data-id="text-field-container" >
        <TextField label={label} className={className} {...otherProps}>
          <Input ref={this.inputRef} onFocus={this.showRef} />
        </TextField>
      </span>
    );
  }

  ...

}
```
returns `{current:null}`

However, although placing the **ref** on the `<TextField>` component returns the correct _TextField_ React object, doing this causes a problem because the TextField's `inputComponent_` property that points to the input DOM object is private - accessing it directly is an antipattern and is not allowed in TypeScript.

**Comment by moog16** [comment]
Hmm I thought this was working in the current 0.7.1. I'm actually working on the typescript changes, and it seems to be working in there. See https://github.com/material-components/material-components-web-react/pull/550/files#diff-dcfa955733f88f24f3c6fd3405e92eff

Will that address your issue?

**Comment by moog16** [comment]
And great detail btw! Ace for github issues

**Comment by vanillabeach** [comment]
Hi,

I have tested on v0.8.0 and it now seems to be working, so am closing this ticket.

FYI, i was able to achieve what i needed by doing the following:

```
setFocus(event: React.FocusEvent<HTMLTextAreaElement>) {
  if (event && event.target) {
    event.target.select();
  }
}

...

render() {
  const { className, label } = this.props;

  return (
    <span data-id="text-field-container" >
      <TextField label={label} className={className}>
        <Input value={someKindOfReactStateValue} onFocus={this.setFocus} />
      </TextField>
    </span>
  );
}
```

Thanks for all the hard work!

**Comment by moog16** [comment]
Thanks for closing :)
