### ISSUE TITLE
Centralised documentation

### ISSUE THREAD

**Issue by kochie** [material-components/material-components-web-react#55]
It's great that each component has documentation but it's a bit annoying to jump between each folder in GitHub. Maybe creating a hub page as part of the README would be a good idea. I'm willing to give it a shot if there are no objections?

**Comment by moog16** [comment]
Yup we hear you! We do need to have another form of documentation. We were actually thinking of creating a site with interactive demos, such as Stackblitz.

Could you describe what you're hub page would be like? Is this a hosted site? A Github pages type of thing? You can of course build whatever you desire, and all of us here would certainly appreciate it.

**Comment by kochie** [comment]
Stackblitz is great, even something like [material-ui](https://material-ui-next.com/) would be great as well.

I was thinking of something more short term and simple such as adding a small description of each working component to the root `README.md` and linking to each packages `README.md` from there.

**Comment by moog16** [comment]
Ya material-ui or (react toolbox)[http://react-toolbox.io/#/components] are similar. I've reached out to them to see what they use. Do you know what tool that is?

RE your last request. Would you want to give it a shot and open a PR? Sounds like you have a good idea.

**Comment by kochie** [comment]
Yeah will do - working on it at the moment.

**Comment by moog16** [comment]
Thanks @kochie! That'll be greatly appreciated. Depending on what you come up with I might also add a Getting Started. Similar to https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md.
