### ISSUE TITLE
ReferenceError: Element is not defined on SSR

### ISSUE THREAD

**Issue by lucasecdb** [material-components/material-components-web-react#561]
Hello, I'm getting a `ReferenceError: Element is not defined` when I try to SSR the Drawer component, running on version 0.7.1.

The issue is probably some optimization on the webpack build process where it removes "dead-code", because the error occurs on the `tabbable` npm package, imported from `focus-trap`, specifically on [this line](https://github.com/davidtheclark/tabbable/blob/master/index.js#L16). But, as you can see, it has a check specifically to avoid this issue when running on node environments. I have checked the minified code and have confirmed that the check for the `typeof Element` is optimized away.

Unfortunately I don't have a reproducible codesandbox snippet as it doesn't execute the code with SSR 😔

**Comment by moog16** [comment]
There was an issue a while back where someone couldn't render the list correctly because of minification (https://github.com/material-components/material-components-web-react/issues/492). 

What does the `typeof Element` become in the minified code? Sadly this isn't our code and we don't have much control over it. Perhaps what I could do is not run the uglifier over the `focus-trap` package.

**Comment by lucasecdb** [comment]
In the minified code it doesn't have the `typeof Element` ternary, just the part after the colon.

> Perhaps what I could do is not run the uglifier over the `focus-trap` package.

Yeah, this should work. Also, it would be nice to have a test case covering this issue, so it doesn't happen again accidentally.

**Comment by lucasecdb** [comment]
```js
function _(module,exports) {
  var candidateSelectors = ['input','select','textarea','a[href]','button','[tabindex]','audio[controls]','video[controls]','[contenteditable]:not([contenteditable="false"])'];
  var candidateSelector = candidateSelectors.join(',');
  var matches = Element.prototype.matches || Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;
   
  function tabbable(el,options) {
    // ...
  }
  // ...
}
```

This is how the `tabbable` package is on the `index.js` inside the dist folder of the npm module. What I find weird is that on the 0.6.2 version, the ternary is still there, just as on the actual package.

**Comment by moog16** [comment]
So this effectively disappears? `typeof Element === 'undefined'
  ? function () {}`

**Comment by lucasecdb** [comment]
Yeah, exactly.

**Comment by moog16** [comment]
Also I think we switched from `react-focus-trap` to `focus-trap` during v0.7.0. So that could be why its still in v0.6.2.

**Comment by moog16** [comment]
I have an idea: add this package to the externals during the `npm run build` step. This should force the drawer package to look at `node_modules` instead of trying to minify it. I think this should work

**Comment by lucasecdb** [comment]
adding it as an external mean it'll be a peer dependency?

**Comment by moog16** [comment]
Adding it as a dep to this object: https://github.com/material-components/material-components-web-react/blob/master/packages/webpack.config.js#L89

**Comment by 4cm4k1** [comment]
Hi, I just saw this and realized it's related to the poorly worded issues I filed. Maybe it would help to reference them here: https://github.com/material-components/material-components-web-react/issues/462 https://github.com/material-components/material-components-web/issues/4104

**Comment by moog16** [comment]
Thanks @4cm4k1! Seems like it is a MDC Web issue not react issue. I still haven't had the chance to look into this one. I will prioritize this on my end since its Web related.

**Comment by alexanderjeurissen** [comment]
@moog16 @4cm4k1 issue https://github.com/material-components/material-components-web/issues/4104 has been resolved, the fix (upgrading focus-trap dependency for the drawer component has been merged. We need to await a new release and bump the mdc-web dependency accordingly to resolve this for materila-components-web-react.

**Comment by moog16** [comment]
@alexanderjeurissen MDC Web will release their next cut this Monday. We will be skipping v0.42.0 and going straight to v0.43.0.

**Comment by moog16** [comment]
This hasn't been slated for 0.9.0 but seems like a blocker for some people. Can someone update to 0.43.0 when it is landed next week? 

The main contributors of this project are moving to MDC Web's typescript conversion project (which will last for about 1 - 3 months). All issues/prs will be reviewed, however we will not be able to contribute. I will add more detail in our Roadmap, but just wanted to see if there are any volunteers who could fix this.

**Comment by 4cm4k1** [comment]
@moog16 Is it just updating the package.json to use 0.43.0 of MDC Web? Or I guess I'll see what you add to the roadmap. Since most of these SSR things are kinda blockers for me, I'd be happy to volunteer to help with this.

**Comment by moog16** [comment]
awesome! Yes its updating to 0.43.0 (come 1/7/19). I don't think drawer has any actual changes.

**Comment by lucasecdb** [comment]
So, I've figured that with the code from #706, you can add the following to your `package.json` to fix the SSR problems I was having:

```json
{
  "resolutions": {
    "@material/ripple": "1.0.0-0",
    "@material/tab-scroller": "1.0.0-0",
    "@material/drawer": "1.0.0-0"
  }
}
```

If you do not want to wait for the code to be released, you can [`link`](https://docs.npmjs.com/cli/link.html) the built package from the rc0.11.0 branch and link it in your repo. I'm closing this since the fix was already merged.

**Comment by 4cm4k1** [comment]
Wow, awesome! Thanks, @lucasecdb! Also, thanks @moog16; I'm sorry I didn't have time to continue working on my PR related to this. I started a new software engineering job, so that has been taking a lot of my time lately, though I think as I settle in there, I will be able to spend more of my time on GitHub again. 💜

**Comment by moog16** [comment]
@lucasecdb thanks for finding a fix for this. I finally have some more bandwidth now that we will be releasing 1.0.0 next week. Going to try upgrading all the packages. :)
