### ISSUE TITLE
Linear progress React MDC component is missing

### ISSUE THREAD

**Issue by javitrevino** [material-components/material-components-web-react#580]
The Linear Progress React component URL is empty, leads to a 404 Github Page.

**Comment by moog16** [comment]
@javitrevino are you talking about this page: https://github.com/material-components/material-components-web-react/tree/master/packages/linear-progress

OR

Are you talking about npm? I was able to `npm i @material/react-linear-progress` without any issue this morning.

**Comment by moog16** [comment]
looks like the typo was the problem. Closing...
