### ISSUE TITLE
ripple: HTMLElement is not defined on SSR

### ISSUE THREAD

**Issue by 4cm4k1** [material-components/material-components-web-react#581]
Hello,

With the changeover to TS in `v0.8.0`, the following [line](https://github.com/material-components/material-components-web-react/blob/v0.7.1/packages/ripple/index.js#L65) went from being scoped within a function to [not](https://github.com/material-components/material-components-web-react/blob/v0.8.0/packages/ripple/index.tsx#L29):
```js
const MATCHES = util.getMatchesProperty(HTMLElement.prototype);
```

In SSR React apps, this will result in an `HTMLElement is not defined` error, because it's not evaluated in a browser where `HTMLElement` would exist.

The following line, when added just before the line above, resolves the issue locally:

```ts
const HTMLElement = typeof HTMLElement === 'undefined' ? function () {} : HTMLElement;
```

However, I'm not sure this is an appropriate solution outside of my use case. If this addition would suffice, I can submit a PR for it. Let me know! Thanks! 😄

**Comment by moog16** [comment]
Thanks for opening the issue..SSR isn't something we're setup for testing, but i'm sure a lot of people out there are using it. Please open PR if you have time. 

I also opened issue #588 since you're the 4th issue regarding SSR.

**Comment by 4cm4k1** [comment]
Hey @moog16, happy New Year! I’ll get to work on a PR. Shouldn’t take too long. Regarding SSR generally, I’ll also look into how RMWC goes about testing against SSR use cases and add what I learn to #588 (not sure about an ETA for this part, though).

**Comment by moog16** [comment]
sweet! ya don't worry too much about exploring how RMWC tests SSR. I will be looking into...eventually. I need to meet with the team to see where it fits into 2019.

**Comment by 4cm4k1** [comment]
As promised, PR submitted! 😉 (First one closed because I forgot to create a new non-master branch.)

**Comment by moog16** [comment]
Thanks :)

**Comment by moog16** [comment]
closing as #592 was merged. Thanks again!
