### ISSUE TITLE
TextField/Icon missing adapter methods `notifyIconAction`,`registerInteractionHandler`, and `deregisterInteractionHandler`

### ISSUE THREAD

**Issue by mgr34** [material-components/material-components-web-react#585]
Textfield/Icon is missing adapter methods `notifyIconAction`, `registerInteractionHandler`, and `deregisterInteractionHandler`. At the moment the latter two  are there to determine if the Icon has been activated from click or keydown events. 

I also note that it appears the material-components-web project has been removing de/registerInteractionHandlers in a lot of their adapters. With the preference to call register eventHandlers in `initialSyncWithDOM()`. This makes me wonder if these may also be removed in a future release.  Therefore, might only `notifyIconAction` be implemented?

**Comment by moog16** [comment]
@mgr34 yes Web has been removing the register/deregister since it doesn't work well with modern frameworks. I believe that's why we left it out. There are a few issues outstanding with text field, and I believe that text field might be refactored in the coming year. 

In the meantime we can implement notifyIconAction adapter method.

**Comment by mgr34** [comment]
@moog16 Thanks for shedding some light onto the thought process of the removal of register/deregister. I was wondering why I was being removed. 

as far as implementing  `notifyIconAction` I will try to get a PR together later this week.  I will leave out the de/registerInteractionHandler.

**Comment by moog16** [comment]
awesome! thanks so much. Before you dive in what are you planning on it being set to? Like a `prop.functionName` that another developer could pass into the component?

**Comment by mgr34** [comment]
Yeah that is inline with that I am thinking. In a previous implementation I went with `onSelect`

```js
notifyIconAction: () => this.props.onSelect()
```

**Comment by moog16** [comment]
Cool. that's what I was thinking. Although I don't think `select` is a good term to use here. What do you think about onIconSelect or onIconToggle. I think `icon` should be in the prop name.

**Comment by mgr34** [comment]
@moog16 I do not really have a strong opinion. I suppose the argument for `onSelect`  is  that this a separate component  `<Icon>`. If this was on a prop on `<TextField>`   `onIconSelect` would be more descriptive.  Here it just adds verbosity and stylistically it may increase the likelihood for a developer having to add a line-break. Seems like a weak argument either way. What would you prefer?

**Comment by mgr34** [comment]
Well looking at the Spec [0] It seems the Icons are not being toggled, like an `<IconButton>` might. Instead they might be used to perform an action. Such as clearing the input, expanding a datepicker, or maybe a dropdown menu. Therefore it seems to function as more as action than a boolean toggle. 

onSelect is already apart of React's event system. Which to me is an argument for onSelect. It lets the React user new to the project feel comfortable. Something custom may indicate there is something to know behind the action. but I could see where that might also be used for an argument against onSelect. In which case something like `handleInteraction()` might work? 


[0] https://material.io/design/components/text-fields.html#anatomy

**Comment by moog16** [comment]
ya i was just thinking maybe `onInteraction` is more appropriate. But good argument for not using toggle. I think select or interaction is good. Thanks for convincing me
