### ISSUE TITLE
drawer - Element is not defined in SSR build

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#594]
similar to #581 

While testing out the PR fix for #581, I also stumbled on to a build error on drawer.

```
ReferenceError: Element is not defined
    at Object.105 (/usr/local/google/home/mattgoo/Downloads/material-next-template-master/node_modules/@material/drawer/dist/mdc.drawer.js:809:15)
    at __webpack_require__ (/usr/local/google/home/mattgoo/Downloads/material-next-template-master/node_modules/@material/drawer/dist/mdc.drawer.js:35:30)
```

This requires a similar fix to #581 found in https://github.com/material-components/material-components-web-react/pull/592.

**Comment by 4cm4k1** [comment]
It looks like this comes from `@material/drawer`, not `@material/react-drawer`, because of `tabbable` (https://github.com/davidtheclark/tabbable/blob/3.1.2/index.js#L14), but the MDC Web team landed this fix which should be in their next release: https://github.com/material-components/material-components-web/pull/4217 😄

**Comment by moog16** [comment]
ah you're right...this is a duplicate. Thanks @4cm4k1

**Comment by rustemgareev** [comment]
I'm using the latest version of `@material/react-drawer` (0.11.0) and still having this issue on my SSR project (built using [Next.js](https://github.com/zeit/next.js/)). I tried to add `resolutions` to my `package.json` as recommended [here](https://github.com/material-components/material-components-web-react/issues/561#issuecomment-468850321) but had no luck. Any chance to get it fixed?

**Comment by rustemgareev** [comment]
`@material/react-drawer` v0.6.2 works fine though.

**Comment by moog16** [comment]
@rustemgareev we haven't updated to the latest mdc web v1. We're currently working on it. Progess is tracked through #697.
