### ISSUE TITLE
<Button> : Problems using TypeScript

### ISSUE THREAD

**Issue by vanillabeach** [material-components/material-components-web-react#610]
Hi,

I am using the `<Button>` component for a trivial [Storybook](https://storybook.js.org/) example that I have written in TypeScript. I have based my code on the [example code](https://github.com/material-components/material-components-web-react/tree/master/packages/button) you have provided in the README doc. 

My code looks like this:

```
import * as React from "react";
import { Button } from "@material/react-button";
import "@material/react-button/index.scss";

const button = () => <Button>Test</Button>;

export { button as Button };
```
However, both VSCode and Storybook give the following error:

> TS2322: Type '{ children: string; }' is not assignable to type 'ButtonProps<ButtonTypes>'.
  Property 'initRipple' is missing in type '{ children: string; }'.

It seems that the ripple functionality is interfering with the default use of the `<Button>`. It would be great if you could provide a TypeScript example (with and without Ripple) so that I can better see the implementation :)

**Comment by vanillabeach** [comment]
Hi,

My colleague took a look at the component and was able to make it work with the following code:

```
import * as React from "react";
import {
  Button as XButton,
  ButtonProps as XButtonProps
} from "@material/react-button";
import { withRipple } from "@material/react-ripple";

import "@material/react-button/index.scss";

type ButtonTypes = HTMLAnchorElement | HTMLButtonElement;
type Props = XButtonProps<ButtonTypes> & {};

const ButtonWithoutRipple = (props: Props) => (
  <XButton {...props}>{props.children}</XButton>
);

const Button = withRipple<Props, ButtonTypes>(ButtonWithoutRipple);

export { Button };
```

Hope this helps!

**Comment by moog16** [comment]
Ah great! Sorry that you need that work around...does that mean you're not able to upgrade typescript versions? Was that even one of the causes?

**Comment by vanillabeach** [comment]
We're using typescript@3.1.2, webpack@4.26.0, and storybook@4.0.0-alpha.3

It's a pretty specific combination of technologies, and we're managing it using lerna. I guess something is getting lost in translation somewhere. We managed to wrap the `<Textfield>` without any problems, so i'll let you know if i experience the same issues with further MDCReact components.

Thanks for looking into it :)
