### ISSUE TITLE
menu-surface hoist option

### ISSUE THREAD

**Issue by aluminick** [material-components/material-components-web-react#614]
I think we need a hoist option. If a menu-surface inside a fixed header is hoisted, it doesn't stay in place when scrolling.

**Comment by moog16** [comment]
@aluminick, you mean like an override? Right now it is hoisted by default always.

**Comment by aluminick** [comment]
Yes an override.

**Comment by aluminick** [comment]
@moog16 it's working as expected now I just added the `fixed` prop. Thank you sir.
