### ISSUE TITLE
Question: React dependency not a peer dependency?

### ISSUE THREAD

**Issue by jasonkylefrank** [material-components/material-components-web-react#616]
Hello!

My team is considering using this library.  One thing that we were wondering about is why React and React-DOM is only listed in `package.json` as a `devDependency` and not as a `peerDependency` also?  

One thing that we're trying to determine is what versions of React would work with this library.  For example, we have a situation where we need to use an older version of React (15.x).  Since React is not listed as a peer dependency in this library's `package.json`, we are not able to determine if something in this library would break with an older version of React.

Thanks for your help!

**Comment by moog16** [comment]
@jasonkylefrank this is actually a bug and React/ReactDOM Should be part of dependencies. This has never come up as an issue to anyone else though so it was deprioritized.

There are some things that we use such as React.Fragments that would break using React 15.x. I'm not sure if the compiled version would work for you. Do you have any insight?

**Comment by jasonkylefrank** [comment]
Hi @moog16!  Just to clarify, you're saying that the `peerDependencies` should be the same as what is listed in the `devDependencies`?  That is:
```
"react": "^16.4.2",
"react-dom": "^16.4.2"
```
Regarding whether or not the compiled version would work in a React 15.x codebase, I do not have any insight.  😀

**Comment by moog16** [comment]
@jasonkylefrank correct it should be at minimum `v16.x.x`. Thanks for raising this as I need to fix how deps are handled in all these packages.

**Comment by HGS-areichma** [comment]
React is listed as a full dependency rather than a dev dependency in each of the individual packages (e.g. `packages/card/package.json`). Does that need to change also?

**Comment by thdk** [comment]
I came here due to the following error in my console and following the information from the link in the error:

> Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
>1. You might have mismatching versions of React and the renderer (such as React DOM)
>2. You might be breaking the Rules of Hooks
>3. You might have more than one copy of React in the same app
>See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

It turns out number 3 is causing the error in my applications which leaded me to this issue here.

Should'nt each package here (ex. @material/react-text-field, @material/react-checkbox,...) have 'react' as a **peer dependency** as suggested in the documentation listed above?

**Comment by moog16** [comment]
Correct, as stated in the previous comments, we agreed react should be changed to a peerDep from dep.

**Comment by thdk** [comment]
I've gone through all package.json files and changed react and react-dom to peer dependencies.

Is that all that must happen? #940

**Comment by moog16** [comment]
Thanks @thdk!
