### ISSUE TITLE
Upgrade resemblejs to version 3

### ISSUE THREAD

**Issue by gugu** [material-components/material-components-web-react#626]
Current version of ResembleJS uses not supported canvas 1.6, which does not build on new Ubuntu anymore. Upgrading to v3 should not break anything and will use canvas 2.0

**Comment by moog16** [comment]
@gugu...please open PR and I can take a look. I guess it depends on if the API changed, but if it didn't then it should be an easy changeset.

**Comment by moog16** [comment]
@gugu...please open PR and I can take a look. I guess it depends on if the API changed, but if it didn't then it should be an easy changeset.
