### ISSUE TITLE
Feature Request : <Select> with enhanced menu

### ISSUE THREAD

**Issue by vanillabeach** [material-components/material-components-web-react#627]
Hi,

I've noticed that the `@material/react-select` component is missing the ability to render the "enhanced" dropdown menu as shown in the [MDC Spec](https://material-components.github.io/material-components-web-catalog/#/component/select) (i.e. the use of MDCMenu)

Do you know when this will be available?

**// John**

PS: These components are super-useful!

**Comment by moog16** [comment]
@vanillabeach great to hear! And yes we do have plans to implement that, however most of the MDC React team has been moved to MDC Web for this month/next month. We don't have the bandwidth to work on that just yet. See [Updated Roadmap](https://github.com/material-components/material-components-web-react/blob/rc0.9.0/ROADMAP.md).

Issue also being tracked here: https://github.com/material-components/material-components-web-react/issues/242

**Comment by vanillabeach** [comment]
Thanks for letting me know. I'll close this issue since it's already being tracked.
