### ISSUE TITLE
menu-surface Hoist anti-pattern?

### ISSUE THREAD

**Issue by aluminick** [material-components/material-components-web-react#628]
https://github.com/material-components/material-components-web-react/blob/1d0870073bdf2d6753b286f83e1476d6db3f0265/packages/menu-surface/index.tsx#L170-L172

Is this an anti-pattern? I think portal should be used on this one.

**Comment by moog16** [comment]
@aluminick I am not familiar with react.portals, but after reading the [docs](https://reactjs.org/docs/portals.html) I believe you to be correct. Would you like to take a crack at it?

**Comment by aluminick** [comment]
@moog16 sure. Thanks.

**Comment by aluminick** [comment]
@moog16 Sorry, I forgot about this issue.
I've hoisted menu-surface using ReactDOM Portal but it has to be wrapped. And the tests are failing.

**Comment by moog16** [comment]
Oh great - do you have a branch already? Whenever you're ready please feel free to open a PR.

**Comment by moog16** [comment]
Closed with #693
