### ISSUE TITLE
Make screenshot-uploads bucket public for read

### ISSUE THREAD

**Issue by gugu** [material-components/material-components-web-react#635]
There is nothing secret (I think) in this folder

If all files there will be public, I can update `npm run test:image-diff` and `travis.yml` file to download files from this bucket using public URL if there is no `MDC_GCLOUD_SERVICE_ACCOUNT_KEY` present.

It will make tests for pull requests to be green if no golden files changed. And as soon as maintainer uploads the new golden - pull requests will become green as well

For the repository tests will run as usual because it has `MDC_GCLOUD_SERVICE_ACCOUNT_KEY` set for travis

**Comment by moog16** [comment]
@gugu can you try now? https://console.cloud.google.com/storage/browser/screenshot-uploads

**Comment by gugu** [comment]
Thanks. Created #638

**Comment by moog16** [comment]
closing. looks like it is working..this saves a ton of time!

**Comment by moog16** [comment]
Sorry - I jumped the gun on closing this. I'll review #638

**Comment by gugu** [comment]
Thanks
