### ISSUE TITLE
react-button contains old CSS (v0.9.0)

### ISSUE THREAD

**Issue by gugu** [material-components/material-components-web-react#643]
Looks like `@material/react-button` component in v0.9.0 contains CSS from `@material/button` v0.41.0, not v0.43.0

**Comment by moog16** [comment]
@gugu we haven't updated any of the components since v0.7.0. Most/all are still on 0.41.0. I haven't had time to go back and update.

**Comment by gugu** [comment]
The problem is that `trailingIcon` parameter requires @material/button v0.43.0. Currently react-button has v0.43.0 as JS requirement and includes CSS from v0.41.0

**Comment by moog16** [comment]
@gugu yes you're right per usual. I'll work on fixing that today and try to get it pushed to npm.

**Comment by moog16** [comment]
@gugu please try it out now. Closing as I tested v0.9.2

**Comment by gugu** [comment]
Thanks
