### ISSUE TITLE
Migrate from deprecated lifecycle componentWillReceiveProps 

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web-react#65]
Some of the packages use deprecated react lifecycle method `componentWillReceiveProps` (Please see [deprecation note](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops)).

It should use `getDerivedStateFromProps` instead.

**Comment by moog16** [comment]
@abhiomkar Thanks for bringing that to my attention. Looks like we will have until v17. It'll be on my radar, but don't think I'll be able to get to it this next release.
