### ISSUE TITLE
chore update Copyright to 2019.

### ISSUE THREAD

**Issue by mgr34** [material-components/material-components-web-react#655]
Majority of files still read

 ```js
 // The MIT License
 //
// Copyright (c) 2018 Google, Inc.
```

this should be updated to 2019

**Comment by kfranqueiro** [comment]
The copyright notices in our files typically reflect the year of first publication, which is why many of them contain 2018 in this repository (and possibly earlier in MDC Web).

**Comment by mgr34** [comment]
That is a very rational decision. I'll close this issue. 

@kfranqueiro Should I resist the urge to update 2018 to 2019 when preparing PR's for other issues?

**Comment by kfranqueiro** [comment]
Yeah, don't worry about updating copyright in existing files, unless it's a full-blown rewrite.
