### ISSUE TITLE
List with conditional false children error

### ISSUE THREAD

**Issue by madaz** [material-components/material-components-web-react#663]
List component fails on false conditional `&&` children.

Overview

```
// where showDivider = false

<List>
  <ListItem>
     <ListItemText primaryText="Item 1" />
  </ListItem>
  { showDivider && <ListDivider /> }
</List>
```
Example https://codesandbox.io/s/2r86yyvpp

The  `list/index.tsx.isListItem` is not handling `null` element which is what is passed in when a false condition is triggered

```
function isListItem(element: any): element is ListItem {
  return element.type === ListItem;
}
```

Should be 

```
function isListItem(element: any): element is ListItem {
  return element && element.type === ListItem;
}
```

Work around is to create a custom If component e.g. `<If condition={showDivider} truthy={<ListDivider/>} />`

I would send a PR but struggling to get the project working on a Windows 10 development environment.

**Comment by moog16** [comment]
Thanks for opening. Yup definitely a bug. Once we merge your current PR, we can hopefully open a PR to fix this.

**Comment by moog16** [comment]
#674 fixes it
