### ISSUE TITLE
Add Getting Started Readme

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#67]
Should provide a start to finish on how to build and app using our components. Similar to https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md.

Instead ours will start with `create-react-app` and then move into building a button on the page.

**Comment by jimbojetlag** [comment]
This is great and much needed!

create-react-app 1.x does not support sass. Are you planning to base the guide on CRA 2.0 which is in alpha?

If it's going to be by importing css, and not sass, in CRA 1.x, how can customizing theme happen?
