### ISSUE TITLE
Tab does not implement `setFocusOnActivate`

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#676]
Tab is missing the `foundation.setFocusOnActivate` method and needs to be implemented. There is an issue in the catalog where tabs do not work, and we believe that the active tab is being 'focused' on page load, which is causing a scroll issue.

I believe if we implement this, and setFocusOnActive to false, the scrolling issue will not occur.

**Comment by ben-mckernan** [comment]
I'm also seeing this issue, where the active tab is stealing focus on page load. I can do a PR with a fix if you like. Do you think it should be possible to configure the value passed to `setFocusOnActive` via a prop on Tab?

**Comment by moog16** [comment]
Name is actually: `setFocusOnActivate`.

And yes...prop is expecting a boolean, so perhaps we can have a `focusOnActivate={...}`, like:
```
<Tab focusOnActivate={true or false} ... />
```

Then in the componentDidUpdate, we could have a check for that prop, and call `foundation.setFocusOnActivate(true or false)`. How does that sound?

**Comment by ben-mckernan** [comment]
Great, that is what I had in mind.
