### ISSUE TITLE
Invalid sourceMappingUrls cause build warnings

### ISSUE THREAD

**Issue by garth** [material-components/material-components-web-react#681]
Some /dist files have references to source map files that are not included.

For example `/react-top-app-bar/dist/index.js` has the following reference:

```js
//# sourceMappingURL=top-app-bar.js.map
```

but `top-app-bar.js.map` is not included in the package. There is an `index.js.map` so maybe the reference is just to the wrong file?

This issue seems to affect most packages and causes packaging tools, such as parceljs, to show a warning for each broken reference.

<details>
  <summary>Example build log</summary>
<pre>
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-top-app-bar/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-top-app-bar/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/top-app-bar/dist/mdc.topAppBar.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-material-icon/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-ripple/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-fab/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-text-field/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-button/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-tab-bar/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-tab/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-dialog/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-tab-scroller/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/tab-bar/dist/mdc.tabBar.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-floating-label/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/ripple/dist/mdc.ripple.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-tab-indicator/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/tab/dist/mdc.tab.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/dom/dist/mdc.dom.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/tab-scroller/dist/mdc.tabScroller.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/floating-label/dist/mdc.floatingLabel.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/tab-indicator/dist/mdc.tabIndicator.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-notched-outline/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/react-line-ripple/dist/index.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/textfield/dist/mdc.textfield.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/line-ripple/dist/mdc.lineRipple.js".
⚠️  Could not load existing sourcemap of "../../node_modules/@material/notched-outline/dist/mdc.notchedOutline.js".
</pre>
</details>

**Comment by moog16** [comment]
@garth you're right - What I do is change the name of the main files from `foo-package-name` --> `index`. This is obviously problematic. I will try solving this one before the release this Tuesday.
