### ISSUE TITLE
sass version with NextJS fails due to missing export on deployment

### ISSUE THREAD

**Issue by dohomi** [material-components/material-components-web-react#684]
Hello,
is there a way to use NextJS with this package? The issue I am facing is that I am unable to export SASS_PATH in the build chain, I am receiving following error:
File to import not found or unreadable: @material/typography/mdc-typography.
Do I miss something or is this package currently not able to run on NextJS with enabled sass?
Thanks

**Comment by moog16** [comment]
Personally I haven't used NextJS. In our [Getting Starting w/ Sass Section](https://github.com/material-components/material-components-web-react#add-environment-variable) it outlines environment variables you need to set. Try that out and see if it works for you.

**Comment by TroyTae** [comment]
@dohomi 
Was the import of the custom sass file successful?
Now I'm using sass-node and this module with next.js, it works well!

**Comment by dohomi** [comment]
@TroyTae how do you deploy it to now/serverless? I was looking into some this repo on my next try: https://github.com/4cm4k1/personal-website

**Comment by TroyTae** [comment]
@dohomi 
I deploy all of files in the build directory(.next/**).
Can you build with next command successfully?
If you have this problem only deploy, how about import that sass file directly?

**Comment by dohomi** [comment]
@TroyTae I finally got it up and running. There were missing sass-loader which was preventing the build.
