### ISSUE TITLE
Deprecate Top App Bar renderProps

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#698]
related https://github.com/material-components/material-components-web-react/pull/688

In v0.13.0 deprecate props and methods in top-app-bar/index.ts to support renderProps. This is in favor of compositional declaration of the TopAppBar.

**Comment by moog16** [comment]
@mgr34 did you want to deprecate this since you also added the new top app bar format?

**Comment by mgr34** [comment]
hey @moog16  Sure, I will get to it sometime this week.

**Comment by moog16** [comment]
awesome! Thanks

**Comment by mgr34** [comment]
Hey @moog16 I wont be able to get to it this week after all. I'll aim for sometime next week.  Have a good holiday weekend.

**Comment by moog16** [comment]
no worries! we can push til next release. Have a great long weekend too!
