### ISSUE TITLE
How to make application layout with material-components-web-react?

### ISSUE THREAD

**Issue by jimbojetlag** [material-components/material-components-web-react#70]
Is the application layout:

1. available now in material-components-web-react?
2. something left to material-components-web, even when building apps with material-components-web-react?
3. going to be implemented later in material-components-web-react?

If it's 3, what is a good way of building the layout when starting with material-components-web-react now?

**Comment by jimbojetlag** [comment]
@moog16 That's right. Would there be a React wrapper for that, or should material-components-web-react users use mdc-layout-grid directly?

**Comment by devxpy** [comment]
+1

**Comment by moog16** [comment]
For the time being I would use MDC Web's Layout grid. We are deprioritizing CSS-only components.

**Comment by devxpy** [comment]
How about [this](https://jamesmfriedman.github.io/rmwc/layout-grid)?

Its a wrapper over MWC.

**Comment by jimbojetlag** [comment]
@devxpy It's probably not a good idea to use multiple React wrappers for MDC at the same time.

**Comment by devxpy** [comment]
I tried it and it works pretty well. 

Although I was quite disappointed when I saw that I had to use SASS for a simple margin/gutter modification. 

Can we provide these SASS modifications as props ?

**Comment by devxpy** [comment]
I was a little disappointed when I discovered that I need to use SASS for simple margin/gutter modification. 

Can we provide an abstraction over it, as props maybe?

**Comment by devxpy** [comment]
Haven't tried mixing components..

**Comment by moog16** [comment]
@devxpy MDC Web has the prebuilt CSS, so you don't have to import SASS. Will that work for you?

**Comment by devxpy** [comment]
Just noticed it. Thanks!

**Comment by moog16** [comment]
Closing as we will revisit building out this component in the future

**Comment by devxpy** [comment]
@moog16. 
No, it doesn't.

You actually have to use a custom webpack config to use the SASS stuff.

This makes it INCOMPATIBLE with create-react-app.

See [this](https://github.com/material-components/material-components-web/issues/351) issue.

Since the gutters/margin (and a lot of styling) is controlled using SASS mixin, how do you propose to handle that?

**Comment by moog16** [comment]
@devxpy true, that layout grid needs Sass to be customized. I wrote a doc on how to integrate create-react-app with Sass: https://github.com/material-components/material-components-web-react/blob/master/docs/getting-started.md#step-2-using-sass. Would this help you?

**Comment by moog16** [comment]
@jimbojetlag I actually tried the [recommended way](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc) found on the create-react-app site. So that will actually work. I can work on updating that doc to recommend their way before ejecting.

**Comment by jimbojetlag** [comment]
@moog16 Can I ask why the guide says that using node-sass-chokidar won't work?

By the way CRA 2.0 will have sass support out of the box.

**Comment by moog16** [comment]
@jimbojetlag originally it was the way I was using it. Did you get it working too? The trick for me was to import the `.scss` files from within App.scss.

**Comment by moog16** [comment]
@jimbojetlag Please see if this suffices: https://github.com/material-components/material-components-web-react/pull/94/files.

**Comment by jimbojetlag** [comment]
@moog16 Thank you for the prompt update.

Importing external .scss files in App.scss is the sass way. Of course, this is not aligned with React's philosophy of composition. Styled component would be a more natural fit for styling in React, but I'm not sure how that would play with importing and customizing MDC Web styles.

Your commit looks good to me, only a minor point: You should be able to use the absolute path `@import "@material/react-button/index";` instead of `@import "../node_modules/@material/react-button/index";`.

**Comment by moog16** [comment]
@jimbojetlag thanks for the input. You're correct. I update the PR to reflect your suggestions. Good call!
