### ISSUE TITLE
bug(select): floating label does not float if value is not string

### ISSUE THREAD

**Issue by mgr34** [material-components/material-components-web-react#717]
If `<Select>` value prop is not a `string` mdc-web will not add the `mdc-floating-label--float-above` class and the label will sit atop the text [[0](https://imgur.com/DLCJQFu)]. Select expects its value to be either a `string | string[] | number`. I believe it should only be string to conform to HTMLSelectElement[[1](https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element)]. This differs from the react select implementation which expands the interface to be `string | string[] | number`  [[2](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bdb87d49e550e600cb30658a9542bfe83337eaf9/types/react/index.d.ts#L2077-L2088)].

Specifically this occurs in the foundation handleChange method [[3](https://github.com/material-components/material-components-web/blob/3cc4c6aa48ae8c1a307df542911e28a7808de41f/packages/mdc-select/foundation.js#L141-L162)]. To determine whether it should call `adapter.floatLabel` it calls
 ```js  
const optionHasValue = value.length > 0;
```
which if it was a number value.length would return undefined and would evaluate to false. Additionally string[] would be misleading. First because the Select component does not support multiple values. Second, because e.target.value will only ever return the first selected value. 

## Why not file an mdc-web issue? 

Mainly because this is the proper behavior of the HTMLSelectElement. the html5 spec indicates that the value of select should only be a string[[1](https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element)]. 

## Proposed solution

Change value to only accept `string`.  Additionally, I believe HTMLSelectElement only allows value on the DOMElement[[4](https://html.spec.whatwg.org/multipage/dom.html#concept-element-dom)] and not the ContentAttributes[[5](https://html.spec.whatwg.org/multipage/dom.html#concept-element-attributes)]. React explicitly defines value [[2](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bdb87d49e550e600cb30658a9542bfe83337eaf9/types/react/index.d.ts#L2077-L2088)].. Therefore, assuming I understand it correctly, the type signature for value should also be defined in the Props interface for both `<Select>` and `<NativeControl>`.

---
I spent too much time I don't have going down this rabbit hole. I don't regret it :)

[0] https://imgur.com/DLCJQFu
[1] https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element
[2] https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bdb87d49e550e600cb30658a9542bfe83337eaf9/types/react/index.d.ts#L2077-L2088
[3] https://github.com/material-components/material-components-web/blob/3cc4c6aa48ae8c1a307df542911e28a7808de41f/packages/mdc-select/foundation.js#L141-L162
[4] https://html.spec.whatwg.org/multipage/dom.html#concept-element-dom
[5] https://html.spec.whatwg.org/multipage/dom.html#concept-element-attributes

**Comment by moog16** [comment]
@mgr34 this is an interesting issue because it seems like HTMLSelectElement does not match HTML5 spec. According to HTML5 spec is should be a [DOMString](https://heycam.github.io/webidl/#idl-DOMString). Do I understand you correctly? If that's the case, we should probably open an issue against [react definitelytyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react).

I'm also leaning to agree with you because [MDC Web's adapter.getValue method](https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/adapter.ts#L65) expects type `string`. So I'm thinking we should do this change.

**Comment by mgr34** [comment]
Hi @moog16,

I do not think it is an issue in react definitelytyped because they do extend the HTMLSelectElement interface to `string | string[] | number`. This is a modification made by the react developers and if I am reading their [documentation](https://reactjs.org/docs/forms.html#the-select-tag) correctly it was to make "his makes it so that `<input type="text">`, `<textarea>`, and `<select>` all work very similarly - they all accept a value attribute that you can use to implement a controlled component."


```ts
    interface SelectHTMLAttributes<T> extends HTMLAttributes<T> {
        autoComplete?: string;
        autoFocus?: boolean;
        disabled?: boolean;
        form?: string;
        multiple?: boolean;
        name?: string;
        required?: boolean;
        size?: number;
        value?: string | string[] | number;
        onChange?: ChangeEventHandler<T>;
    }
```

the HTMLSelectElement should not have a value attribute. Insofar as that HTML5 validation [0] is a thing you will see an HTML5 validator throw an error if `<select>` is instantiated with a value attribute. This is because value is a DOM Interface [1] and not a content attributes [2]. I'm afraid I cannot clearly explain the difference at the moment. But the content attributes are the attributes you can set on the element. 


Anyhow, I can prepare a PR in the next day or so changing value to only accept a string. 

---
[0] -- I've spent too much time around XML fanatics blah blah blah.  https://validator.w3.org/nu/#textarea
[1] https://html.spec.whatwg.org/multipage/dom.html#concept-element-dom
[2] https://html.spec.whatwg.org/multipage/dom.html#concept-element-attributes

**Comment by moog16** [comment]
@mgr34 I understand the differences between DomInterface & Attributes. They have the same syntax and look the same, but the browser and other frameworks treat them differently. 

Since MDC Web has value strictly as string, I'm fine with changing it.

**Comment by mgr34** [comment]
Great--I'm glad I didn't need to explain further. :) I was having a hard time putting it into words as I was rushing out the door yesterday evening.

**Comment by moog16** [comment]
Awesome - thanks for doing all that research. You made a convincing argument.
