### ISSUE TITLE
How to change a two-tone color icon?

### ISSUE THREAD

**Issue by heliocosta** [material-components/material-components-web-react#730]
Hi there, I've managed to use the two-tone Material icon, however, I the colours aren't changed. I've tried everything but no success at all. 

Current colours
![image](https://user-images.githubusercontent.com/1838945/54199817-c3734880-44c1-11e9-960d-acfa25fb3285.png)

Expected behaviour
![image](https://user-images.githubusercontent.com/1838945/54199899-e7368e80-44c1-11e9-850b-9f61d7c1ff70.png)

**Comment by moog16** [comment]
Are you using Sass mixins? Or CSS overrides? A codepen or some sample code would help to help you :)

**Comment by heliocosta** [comment]
Hi @moog16 

I've created this repl.it with the code: https://repl.it/@heliofc/QuintessentialDeadRay

**Comment by moog16** [comment]
@heliocosta I couldn't get the repl.it to work, but I did create a CRA to test it. Did you find all those css rules from https://google.github.io/material-design-icons/#icon-font-for-the-web? I think those docs are very old, and we've contacted the fonts team to update it. 

In the meantime as a workaround you could go to https://material.io/tools/icons/?style=baseline, and download the SVG icons. You can host them from your app locally and style individual tags. Not the greatest, but if its only need to style 1 or 2 icons then this should work until we have an answer from the icons team.

**Comment by moog16** [comment]
@heliocosta the different icon font variants is a new feature and doesn't have color capabilities yet. As this isn't a MDC React issue I am going to close it. We hopefully should see color customization for variants within the next month.

**Comment by McGregor25** [comment]
I tried to do it with the color property: of css but it did not work, apparently it does not allow to paint them, the only way I have found to paint them is with filter, but it does not make much sense, the right thing would be to use the property {color: color;} or at least {background-color: color} but being a font does not allow me to do this last.

**Comment by codekidX** [comment]
For anyone looking for answers set the `htmlColor` property.

**Comment by createdbyken** [comment]
Hey guys! I managed to get a solution for this:

check the codepen I made: https://codepen.io/themau5/pen/QWwaYKR
Also you should check this tool to change colors with filters: 
https://codepen.io/sosuke/pen/Pjoqqp

Hope is helpful for all of you

**Comment by codedthemes** [comment]
Its not the proper solution. Below IE13 filter property not works.

**Comment by createdbyken** [comment]
> Its not the proper solution. Below IE13 filter property not works.

I just managed to get a walkaround.

**Comment by tanvesh01** [comment]
Did anyone find the solution to this? it's been more than a year now.

**Comment by beagley** [comment]
A lot has changed with this. See https://fonts.google.com/icons and click **How to Implement / Developer Guide**.

There are 5 different styles of icons you can pick from. It looks like you are trying to style a "two-tone" icon into the "outlined" style. Link to the font, and then try `<span class="material-icons-outlined" style="color:purple;">lock</span>`

**Comment by rocketraman** [comment]
The only solution to this is still the filter workaround mentioned by @createdbyken above? The Developer Guide mentions using the `color` style to color icons, but that doesn't seem to work for "two-tone" icons.

**Comment by abrarzahed** [comment]
Try this:
                     -----------------------------------------------
                     <span  class="material-icons-two-tone   your-custom-class">school</span>
                      .your-custom-class {
                          color: transparent;
                          background: var(--your-color);
                          background-clip: text;
                         -webkit-background-clip: text;
                     }

**Comment by hrieke** [comment]
And it's November, 2023.  Abrarzahed's solution is still the one that works.

**Comment by mairead** [comment]
July 24, Abrarzahed's solution looks great in Chrome but sadly not in Safari, I think perhaps because they treat transparency differently

**Comment by tiuvi** [comment]
The only thing that works decently is copying the icon
```
globalThis['SvgFavorite'] = (props) => {
  
  const {
    color= "black",
    background="red",
    opacity=1,
    ...others
  } = props;
       
  return(
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    {...others}
  >
    <path style={{fill: background}}
      d="M16.5 5c-1.54 0-3.04.99-3.56 2.36h-1.87C10.54 5.99 9.04 5 7.5 5 5.5 5 4 6.5 4 8.5c0 2.89 3.14 5.74 7.9 10.05l.1.1.1-.1C16.86 14.24 20 11.39 20 8.5c0-2-1.5-3.5-3.5-3.5z"
      opacity={opacity}
    />
    <path style={{fill: color}}  
    d="M16.5 3c-1.74 0-3.41.81-4.5 2.09C10.91 3.81 9.24 3 7.5 3 4.42 3 2 5.42 2 8.5c0 3.78 3.4 6.86 8.55 11.54L12 21.35l1.45-1.32C18.6 15.36 22 12.28 22 8.5 22 5.42 19.58 3 16.5 3zm-4.4 15.55-.1.1-.1-.1C7.14 14.24 4 11.39 4 8.5 4 6.5 5.5 5 7.5 5c1.54 0 3.04.99 3.57 2.36h1.87C13.46 5.99 14.96 5 16.5 5c2 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.9 10.05z" />
  </svg>
)};
```
It seemed a bit of a mess to me so I came here to see if anyone already had the solution but I see that they don't.
