### ISSUE TITLE
How to acess native element via Typescript?

### ISSUE THREAD

**Issue by SandHilt** [material-components/material-components-web-react#731]
How to make same example in Typescript?

https://github.com/material-components/material-components-web-react/tree/rc0.11.0/packages/text-field#accessing-the-native-input-element

**Comment by moog16** [comment]
Are you running into errors? The code should be the same. We actually have a screenshot test written in TS. https://github.com/material-components/material-components-web-react/blob/v0.10.0/test/screenshot/text-field/refTest.tsx

If you're in the root of the directory, you can run the screenshot tests with `npm start` (please follow [getting started guide](https://github.com/material-components/material-components-web-react#getting-started).

**Comment by moog16** [comment]
Did this fix your issue?

**Comment by SandHilt** [comment]
> Did this fix your issue?

@moog16 Why ``input:any`` ?
https://github.com/material-components/material-components-web-react/blob/52eeb522d2779562a1d679a0a552c76148016174/test/screenshot/text-field/refTest.tsx#L17

Because it could not be this?
 ```typescript
input: Input<HTMLInputElement> | null
```

**Comment by moog16** [comment]
There is a bug in text-field/index.tsx. I think we have the typings incorrect here:
```
      ref: (input: Input<T>) => {
        if (typeof ref === 'function') {
          ref(input);
        }
        this.inputComponent_ = input;
      },
```

Ideally the actual typing should be `init: React.Ref<Input<HTMLInputElement>>`

**Comment by moog16** [comment]
Closing as this has gone stale. If you are still having issues. Please open again.
