### ISSUE TITLE
Dialog and drawer have different focus-trap dependency versions.

### ISSUE THREAD

**Issue by evankim390** [material-components/material-components-web-react#795]
[Drawer depends on ^3.0.0](https://github.com/material-components/material-components-web-react/blob/rc0.12.0/packages/drawer/package.json)
[Dialog depends on ^4.0.2](https://github.com/material-components/material-components-web-react/blob/rc0.12.0/packages/dialog/package.json)

Would it be possible to sync the two packages to the same version? This would avoid pulling in multiple copies of the same library, and works slightly nicer with yarn (right now I have to manually resolve `focus-trap` to `^4.0.2`)

**Comment by moog16** [comment]
@evankim390 - yes definitely...I didn't even realize that they were different, but I know how mismatched npm modules can break you environment. Would you be will to open a PR against rc0.12.0?

**Comment by evankim390** [comment]
Sure thing https://github.com/material-components/material-components-web-react/pull/797

**Comment by moog16** [comment]
Closing for #797
