### ISSUE TITLE
Why TabBar arrow dont show in desktop?

### ISSUE THREAD

**Issue by SandHilt** [material-components/material-components-web-react#798]
I'm using react-tab-bar inside of react-top-app-bar.

![image](https://user-images.githubusercontent.com/6170125/55677558-90558680-58c0-11e9-9acd-9c7734f8aa73.png)

But don't show this indicator in desktop.
![image](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1jpIMFm45lawJ7dAGwgbw4rkvUWnRp0oB%2Ftabs-paginated-01.png)
source: https://material.io/design/components/tabs.html#scrollable-tabs

**Comment by ben-mckernan** [comment]
Probably because it is not implemented in material-components-web which this library is based on. See: material-components/material-components-web#3716

**Comment by moog16** [comment]
Correct, this is one of the last feature of tabs that hasn't been implemented from the original version. If you need the scroll bars, you could wrap material-components-web's [mdc-tabs](https://github.com/material-components/material-components-web/tree/master/packages/mdc-tabs). It is deprecated, but won't be officially until we implement it in the new material tabs.

**Comment by moog16** [comment]
Closing since its an mdc web issue.
