### ISSUE TITLE
Masked Input for Text Field

### ISSUE THREAD

**Issue by WhoseSomebody** [material-components/material-components-web-react#800]
Hello everyone!

Firstly, I was looking for an elegant way of adding mask to `Input` from this lib, but didn't find anything about it. So I decided to try to use third-party libs.

As I was already working with [react-text-mask](https://www.npmjs.com/package/react-text-mask), I decided to use it.
So, I replaced `Input` with `MaskedInput`:
```
<TextField
  label={error || label || placeholder}
  className={containerClassName}
  error={error}
  onTrailingIconSelect={this.togglePassword}
>
  <MaskedInput
    {...rest}
    mask={['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/]}
    onKeyDown={this.keyPress}
    onChange={onChange || this.handleInput}
    autoComplete="off"
    className="mdc-text-field__input"
  />
</TextField>
```
where `rest` contains 
```
name: "inputName"
onReturnPress: null
type: "phone"
value: ""
```

But I faced a problem: when I focus on `Input` or input any text neither `floating label` nor `ripple` updates their classes.
![image](https://user-images.githubusercontent.com/5785260/55679670-1f56b300-5942-11e9-89e0-1335157778d3.png)

Sure, I was trying to find in the source code, what makes them update their classes.. but no luck :/

So question for more advised in this lib guys, what can I do either for this `MaskedInput`, so it will fire required events to update `floating label` & `ripple`, or to use mask in the context of already existing solution?

**Comment by moog16** [comment]
So floating label triggers on `this.props.value`. It needs to have a length. Can you just pass it a dummy value if you're masked value is set?

**Comment by WhoseSomebody** [comment]
> So floating label triggers on `this.props.value`. It needs to have a length. Can you just pass it a dummy value if you're masked value is set?

Thanks for reply.
Which `value`? For `TextField` or for inner `MaskedInput`?
I try to update in all of them, but no luck.. and how's about trigger on `TextField` click (when we have an active input)?

**Comment by WhoseSomebody** [comment]
Okay.. I found one pretty ugly method which works
![image](https://user-images.githubusercontent.com/5785260/55777896-ea7a6580-5ad3-11e9-9463-ab9556b88463.png)
```floatingLabelClassName={document.activeElement.name === rest.name || rest.value ? 'mdc-floating-label--float-above' : ''}
lineRippleClassName={document.activeElement.name === rest.name ? 'mdc-line-ripple--active' : ''}```
are passed to `TextField` and to live re-render  
```onFocus={() => this.setState({ animationTrickDummy: animationTrickDummy + 1 })}
onBlur={() => this.setState({ animationTrickDummy: animationTrickDummy - 1 })}```
are passed to `MaskedInput`. 

So it adds required classes depending on rules, because I still cannot find the mechanism (trigger) to make `TextField` do it itself..

I would appreciate more elegant solutions if you have any! 

---------
Another thing which happened after usage of custom input (even a raw `<input />`) inside of `TextField` is this error:
![image](https://user-images.githubusercontent.com/5785260/55778091-8efca780-5ad4-11e9-9ad0-db72ca280233.png)
Not sure I really understand what it means :)
Error happens here..
![image](https://user-images.githubusercontent.com/5785260/55778154-b6537480-5ad4-11e9-9762-79f76d405d6a.png)

**Comment by moog16** [comment]
So the Input and the TextField need to have a direct child/parent relationship. We have a work around, which includes using ReactContext, but we haven't had time to fix that yet. You won't be able to wrap the `<Input>` component without some trickery.

**Comment by WhoseSomebody** [comment]
Okay, I see..
So no way to hide the error?

**Comment by moog16** [comment]
Sorry - not as of right now. If you'd like to implement the text-field and input using react.context we would love the contribution. We do recognize it is no small feat. But you can see my current working branch for menu. You can try to follow [this commit](https://github.com/material-components/material-components-web-react/pull/786/commits/c605cef9d080036f5335e33ef144bf9e44947a49#diff-9e4ae056e8bc14fde35811960a66f6c3R87) to get it to work. LMK if you want to take a stab at it.

**Comment by moog16** [comment]
Closing for https://github.com/material-components/material-components-web-react/issues/811
