### ISSUE TITLE
Refactor literal class name to constants

### ISSUE THREAD

**Issue by TroyTae** [material-components/material-components-web-react#827]
- [x] Button (#838)

- [x] Card (#839)

- [x] Checkbox (#982)

- [x] Chips (#982)

- [x] Drawer (#982)

- [x] Fab (#844)

- [x] FloatingLabel (#845)

- [x] IconButton (#982)

- [x] LayoutGrid (#846)

- [x] LineRipple (#983)

- [x] LinearProgress (#983)

- [x] List (#983)

- [x] MaterialIcon (#983)

- [x] Menu (#983)

- [x] MenuSurface (#983)

- [ ] NotchedOutline

- [x] Radio (#983)

- [x] Select (#983)

- [x] SnackBar (#983)

- [x] Switch

- [x] TabBar

- [x] TabIndicator

- [x] TabScroller

- [x] Tab

- [x] Text Filed

- [x] TopAppBar

**Comment by abhiomkar** [comment]
I created `feat/constants` branch on upstream for future PRs so we can merge to `master` branch at once. Thanks!

**Comment by TroyTae** [comment]
@abhiomkar 
That's nice. Thank you!

**Comment by TroyTae** [comment]
It's going to take a lot of time to merge https://github.com/material-components/material-components-web/pull/4761.
Close this issue and I'll reopen after merging!
