### ISSUE TITLE
SelectIcon not working

### ISSUE THREAD

**Issue by quic5** [material-components/material-components-web-react#837]
I get the following error when i try to import 

> import { SelectIcon } from '@material/react-select/icon/index

```
Module parse failed: Unexpected token (28:7)
You may need an appropriate loader to handle this file type.
| import {MDCSelectIconFoundation} from '@material/select/icon/foundation';
| 
> export interface SelectIconProps extends React.HTMLProps<HTMLElement> {
|   setIconFoundation?: (foundation?: MDCSelectIconFoundation) => void;
|   tag?: keyof React.ReactHTML;
```

I'm using create-react-app with typescript

Any ideas? Is there a bug or am I making a mistake?

**Comment by moog16** [comment]
@quic5 CRA doesn't come with typescript by default out of the box. You might need to setup Typescript. Try that out and let us know how that works.

**Comment by quic5** [comment]
@moog16 it does [https://facebook.github.io/create-react-app/docs/adding-typescript](https://facebook.github.io/create-react-app/docs/adding-typescript)

**Comment by moog16** [comment]
It does - but you have to follow those other steps. But it seems like you already tried that? Also have you tried just importing selectIcon like:
```
import {SelectIcon} from '@material/react-select';
```

I tried recreating this with a create-react-app, and haven't been able to reproduce.

**Comment by quic5** [comment]
Oh yeah I tried to import SelectIcon from `@material/react-select/icon/index` as the [docs](https://github.com/material-components/material-components-web-react/tree/master/packages/select/icon) suggest it. But form `@material/react-select` it works now. Thank you!
