### ISSUE TITLE
Warning while using TypeScript 

### ISSUE THREAD

**Issue by yevhen-ctbto** [material-components/material-components-web-react#841]
By using TypeScript i get warning that some props is required which are not in official documentation.

![image](https://user-images.githubusercontent.com/46522933/57085452-8165c680-6cfc-11e9-997b-8fb5549300e9.png)

**Comment by moog16** [comment]
Someone already opened a PR for a fix: https://github.com/material-components/material-components-web-react/pull/810. Just waiting on fixing tests.

**Comment by moog16** [comment]
opened https://github.com/material-components/material-components-web-react/pull/854 after closing #810

**Comment by moog16** [comment]
Closing since #854 is merged
