### ISSUE TITLE
v0.12.0 typescript does not compile.

### ISSUE THREAD

**Issue by Batbold-Gansukh** [material-components/material-components-web-react#850]
<img width="865" alt="Screen Shot 2019-05-04 at 8 28 42 PM" src="https://user-images.githubusercontent.com/480945/57178985-3e962100-6eab-11e9-8800-3ac16d02a55c.png">

All of the React import seems to be in wrong format.

It should be:
`import * as React from 'react'`

**Comment by cpboyd** [comment]
I don't think you want to do that...
`import *` hinders any possible tree-shaking as you're explicitly stating that you want to import everything.

Further, React's own documentation specifies `import React from 'react';`
See: https://facebook.github.io/create-react-app/docs/importing-a-component

**Comment by Batbold-Gansukh** [comment]
It seems `esModuleInterop` typescript compiler flag is needed to be enabled. Which is by default disabled.

@cpboyd all of Typescript documentation specifies `import * as React from 'react';`

**Comment by cpboyd** [comment]
@Batbold-Gansukh Note [tsconfig.json line 12](https://github.com/material-components/material-components-web-react/blob/master/tsconfig.json#L12) in the root directory.

The latest [create-react-app](https://github.com/facebook/create-react-app) creates TypeScript projects with `"esModuleInterop": true` in tsconfig.json and uses `import React from 'react';`

Perhaps Microsoft's documentation is just outdated?

**Comment by moog16** [comment]
@Batbold-Gansukh - If you're using our TS files, you will also need to enable `esModuleInterop`. This makes it so that we do not need to import all using the `import *...`. And as @cpboyd said, it is enabled as of the v0.12.0 release.
