### ISSUE TITLE
ClientRect is not defined

### ISSUE THREAD

**Issue by cpboyd** [material-components/material-components-web-react#853]
I've noticed that v.0.12 uses `new ClientRect()` in some places...

Well, I've been attempting to implement `mdc-slider` in React, and tried returning a `new ClientRect()` and got a `ClientRect is not defined` error.

Googling took me to: https://github.com/Microsoft/TypeScript/issues/18615

It seems that while TypeScript's typings still have `ClientRect`, Chrome has replaced it with `DOMRect` .

Further, `DOMRect` itself is experimental according to MDN: https://developer.mozilla.org/en-US/docs/Web/API/DOMRect

I'm not sure if these are getting properly polyfilled by Webpack and Babel either.

Was there a specific reason to switch from the explicit `{ top: 0, right: 0, bottom: 0, left: 0, width: 0, height: 0 }` to `new ClientRect()`?

**Comment by moog16** [comment]
@cpboyd - you're correct. These shouldn't have changed. I caught a few cases, but missed these. Would you mind fixing? Otherwise we will try to prioritize for future release. Thanks!

**Comment by moog16** [comment]
closing for #855
