### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by lucasecdb** [material-components/material-components-web-react#860]
can I add a prettier config for more consistent code style? does Google have a default configuration we could use?

**Comment by moog16** [comment]
What is the difference between Prettier and the Eslint Fixer (npm run fix or npm run lint)? Could you achieve the same thing with Eslint? Or is prettier more strict? I looked it up and Google does have a prettier config that we could use. I just want to understand the differences. Thanks!

**Comment by lucasecdb** [comment]
I think prettier is more strict because it works on a line width basis. You can also integrate prettier with eslint, so you can run npm run fix for prettier to run.

**Comment by moog16** [comment]
Would you mind opening a PR for the changes, and see what errors happen? Or do you need the default config?

**Comment by lucasecdb** [comment]
sure! I think I can get some of the style preferences from some files and then you tell me what you think :-)
