### ISSUE TITLE
Error using @material/react-select in TypeScript

### ISSUE THREAD

**Issue by bileschi** [material-components/material-components-web-react#864]
I'm attempting to use @material/react-select in an open source project, but I'm having trouble including it in a TSX file.   I am not having a similar problem with @material/react-button, which works great.

I'm importing @material/react-select like this:

```
import Select, {Option} from '@material/react-select';
```

I'm trying to use it using the demo code from the npm package:

```
 <Select
  label='Choose Dog'
  value={this.state.value}
  onChange={(evt) => this.setState({value: evt.target.value})}
>
  <Option value='pomsky'>Pomsky</Option>
  <Option value='goldenDoodle'>Golden Doodle</Option>
</Select>
```

My IDE (VSCode) is surfacing the following error:

```
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)

Type '{ children: Element[]; label: string; value: any; onChange: (evt: any) => any; }' is not assignable to type '{}'.
  Property 'children' does not exist on type '{}'.ts(2322)
```

I've tried playing around a little, and searching for these errors online, but wasn't able to find anything actionable.

**Comment by moog16** [comment]
Thanks for opening the issue. I did some digging and it looks like you need the `"allowSyntheticDefaultImports": true,` option in your tsconfig. I think this is required since we are building our components with the `esModuleInterop` option, which is not turned on by default in most tsconfig.json.

**Comment by bileschi** [comment]
Thanks!  This worked for me.
