### ISSUE TITLE
latest version mix up `mixins` and `_mixins`

### ISSUE THREAD

**Issue by shaojianwei** [material-components/material-components-web-react#865]
In `./node_modules`, file `@material/button/_mixins.scss` use `@import "@material/elevation/mixins";`, but there is only file `@material/elevation/_mixins.scss`

**Comment by moog16** [comment]
@shaojianwei Sass actually knows to look for `@material/elevation/_mixins.scss` as the leading `_` is known as a [partial](https://sass-lang.com/guide) (see Partial section). 

Are you seeing an issue?

**Comment by shaojianwei** [comment]
> @shaojianwei Sass actually knows to look for `@material/elevation/_mixins.scss` as the leading `_` is known as a [partial](https://sass-lang.com/guide) (see Partial section).
> 
> Are you seeing an issue?

newer to sass. I'm using` react` `webpack` etc. from scratch, so didn't follow repository [Material Components for React](https://github.com/material-components/material-components-web-react) README step by step and met the issue.
I see the partial, change the webpack config file as follows (not completed), it solved.
```js
...
{
  loader: "sass-loader",
  options: { includePaths: [path.resolve(__dirname, "node_modules")] }
}
...
```
Thanks for your patience, I'll learn sass from the ground up.

**Comment by moog16** [comment]
Glad you got it figured out! Thanks for using the components and let us know if you need anymore help :)
