### ISSUE TITLE
.js.flow definitions

### ISSUE THREAD

**Issue by gugu** [material-components/material-components-web-react#878]
Some projects use flow instead of typescript and adding flow definitions will help people

Pros:
* really easy to add
* I already have some of them ready

Cons:
* Maintenance

**Comment by moog16** [comment]
@gugu yeah I realize flow is also a popular library. Is there a way to programatically create them from the TS definitions? Ideally this would be a npm script with 0 maintenance. The only maintenance I would want to incur is if flow updates to a breaking version.
