### ISSUE TITLE
Material transitions with element motion

### ISSUE THREAD

**Issue by madou** [material-components/material-components-web-react#879]
Hi! I develop a library called element motion (see: [elementmotion.com](https://elementmotion.com)) - which is primarily inspired by material animations. I think it would fit lovely with material components.

These days you don't want to re-written everything yourself - element motion has been made to be small, performant, and powerfully customisable - let's talk?

**Comment by moog16** [comment]
Your home page looks great! What would you like from the MDC React team?

**Comment by madou** [comment]
hi there

do you have a roadmap for adding motion to the library (see: https://material.io/design/motion)? yubaba's roots were always to remake the material motion spec for the web, so it's been built with that in mind from day 1.

because of that i think it would go hand in hand with a material design library hehe - either as a supplementary "build your own adventure" using with it - or alternatively it being used as a dependency in the library for out of the box motion.

i have a animations roadmap which im slowly working through (here: https://github.com/madou/yubaba/issues/49) that's all about filling in yubaba's gaps.

so the underlying question is if you're aiming for motion in the future - perhaps there's a spot with yubaba either out of the box or as a cookbook example of how a consumer can get it?

**Comment by moog16** [comment]
Closing as this is not a priority right now. Thanks for opening this issue, and great work on the animations!
