### ISSUE TITLE
[Question] Should labels in textfields be mandatory?

### ISSUE THREAD

**Issue by AllanWang** [material-components/material-components-web-react#882]
From the [current docs](https://github.com/material-components/material-components-web-react/tree/v0.12.1/packages/text-field#props), it says that labels must be mandatory.

However, [mdc docs](https://github.com/material-components/material-components-web/tree/v2.2.0/packages/mdc-textfield#text-field-without-label) shows that fields without labels are possible, and the react logic seems to handle this:

https://github.com/material-components/material-components-web-react/blob/5ee9df0982d6cff893523c3e1e447b0f98bf8611/packages/text-field/index.tsx#L160-L162

Should the docs be updated, or is the field still mandatory for other purposes?

**Comment by moog16** [comment]
Thanks for opening this issue. Docs need to be updated! Currently you can use both the web and react versions of mdc without the label.

**Comment by moog16** [comment]
fixed in #896
