### ISSUE TITLE
Sync to MDC Web v0.36.0

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#90]
https://github.com/material-components/material-components-web/tree/v0.36.0

**Comment by moog16** [comment]
https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#0360-2018-06-04

- textField.icon.adapter `setContent()`
- text-field: registerValidationAttributeChangeHandler adapter API now expects the handler to accept an array of strings, not mutation objects (separate issue: https://github.com/material-components/material-components-web-react/issues/64)

**Comment by kfranqueiro** [comment]
Packages that were updated that exist in MDC React:

* button
* card
* fab
* floating-label
* ripple
* textfield
* top-app-bar
