### ISSUE TITLE
Select 'enhanced' Improper Rendering

### ISSUE THREAD

**Issue by qs-labs** [material-components/material-components-web-react#926]
The Select 'enhanced' prop appears to cause improper rendering with its contents (demonstrated below).
![image](https://user-images.githubusercontent.com/38405319/59364861-8b201800-8d05-11e9-9ebe-deded040ad66.png)

Using the [README code](https://github.com/material-components/material-components-web-react/tree/master/packages/select#enhanced-select) as a template, I created [this app](https://stackblitz.com/edit/react-dmdqhj) to demonstrate the behavior.

I am not sure if this is reproducible behavior, wanted to submit just in case.

**Comment by will-ebm** [comment]
did u import "@material/react-menu-surface/dist/menu-surface.css" ?

**Comment by moog16** [comment]
You actually need to import all of these:

```
import '@material/react-menu-surface/index.scss';
import '@material/react-list/index.scss';
import '@material/react-menu/index.scss';
import '@material/react-select/index.scss';
```

**Comment by moog16** [comment]
opening pr

**Comment by qs-labs** [comment]
Per your suggestions, the expected behavior was accomplished with the following imports:
```
import '@material/react-select/index.scss';
import '@material/react-list/index.scss';
import '@material/react-menu-surface/index.scss';
```
Attempts at importing `import '@material/react-menu/index.scss';` resulted in an error (see [here](https://stackblitz.com/edit/react-dmdqhj?file=Select%2FMyEnhancedSelect.js)). Thank you for your assistance, @will-ebm and @moog16!

**Comment by moog16** [comment]
Hm that's strange as [sass file](https://unpkg.com/@material/react-menu@0.13.2/index.scss) does exist. Might be an issue with turbo modules as well...
