### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by aluminick** [material-components/material-components-web-react#93]
Main components are compile fine except the react version. Why?

**Comment by moog16** [comment]
You're saying that React is throwing an exception? Import is ES6 syntax. I'm not sure about your setup, but you could be missing babel transpiling when importing your dependencies. Do you have a sample project you can share? I can help more easily that way.

**Comment by aluminick** [comment]
`const {
      className,
      raised,
      unelevated,
      outlined,
      icon,
      children,
      initRipple,
      unbounded, // eslint-disable-line no-unused-vars
      ...otherProps // <---- 
    } = this.props;`

Also that triple dot causes an error. :(

**Comment by aluminick** [comment]
Oh i see. So the correct file to import is from `dist` folder and not `import Button from '@material/react-button';` <-- like that?

**Comment by moog16** [comment]
Correct! Does that work for you?

**Comment by aluminick** [comment]
@moog16 thanks!
