### ISSUE TITLE
<form...> won't submit on enter key if there are > 1 TextFields

### ISSUE THREAD

**Issue by ndtreviv** [material-components/material-components-web-react#938]
Reproduce: https://stackblitz.com/edit/react-rjyfbu

I have two `TextField`s in a `form` element. I'm expecting that when I press the enter key, the form will submit and the `onSubmit` will get called. It doesn't.

If I remove a `TextField`, so there is only one, then it works.

**Comment by moog16** [comment]
I didn't know this: https://stackoverflow.com/questions/28709146/form-with-two-inputs-not-submitting

Looks like you need a button in the form for it to work.
