### ISSUE TITLE
Can't override width of focused outlined text field

### ISSUE THREAD

**Issue by andrew-kuzovov** [material-components/material-components-web-react#941]
I've spent lot of time trying to find out how to make border of selected textfield thinner.
My research led me to this private mixin in node_modules\@material\textfield\_mixins.scss:

@mixin mdc-text-field-outlined-focused_ {
  @include mdc-notched-outline-stroke-width(2px);
}

Still, I cannot find the way to override this value, except changing it right in _mixins.scss.
Please provide some documentation for this customization.

**Comment by moog16** [comment]
You will need to import `@import "@material/notched-outline/mixins";`. Then use the follow selector to override the default:


```
.mdc-text-field--outlined.mdc-text-field--focused {
  @include mdc-notched-outline-stroke-width(10px); // whatever you need
}
```

Closing - please reopen if this does not work for you.

**Comment by andrew-kuzovov** [comment]
It works. Thanks!
