### ISSUE TITLE
List applies invalid default aria-orientation attribute

### ISSUE THREAD

**Issue by liamcmitchell-sc** [material-components/material-components-web-react#944]
[mdc-list documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#accessibility) says

> Use role="listbox" only for single selection list, without this role the ul element is implicitely role="list". Do not use aria-orientation attribute for standard list (i.e., role="list"), use component's vertical property to set the orientation to vertical.

The React wrapper applies `aria-orientation="vertical"` in default props: https://github.com/material-components/material-components-web-react/blob/master/packages/list/index.tsx#L117

I think the ideal fix is to refactor the `aria-orientation` prop to `orientation` (enum) or `vertical` (bool) and apply this as `aria-orientation` for allowed role values. But, this would be a breaking change.

This could be fixed without renaming props but it would be a little strange to pass an aria prop that is not passed to the root element. Maybe edgy enough not to worry about.

**Comment by moog16** [comment]
From the [W3 spec](https://www.w3.org/TR/wai-aria-1.1/#list):

> Elements with the role listbox have an implicit aria-orientation value of vertical.

I interpret this and what we say on the MDC Web docs as saying the following:

1. Use role='listbox' when the list selectable
1. Use role='list' (or use `ol`/`ul`/etc.) if list is non-selectable
1. apply `aria-orientation=vertical` when role='list' or when tag is `ol`/`ul`
1. do not apply `aria-orientation=vertical` when role='listbox' as this is implied

Do you agree, or is this in conflict with what you're reading? 

I think regardless MDC React shouldn't be setting aria-orientation by default.

**Comment by liamcmitchell-sc** [comment]
I came across this when reviewing output of [react-axe](https://github.com/dequelabs/react-axe) (runtime a11y auditor).

The [specific error](https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI) is that `aria-orientation` is not supported for `role=list` (the default).

**Comment by moog16** [comment]
Ahh, I can't seem to find the documentation that states aria-orientation is not supported for role=list, but it seems that [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-orientation_attribute#Used_With_ARIA_Roles) states that it is only used on these specific roles. So in fact we should only be setting aria-orientation if those roles are set. That is quite a long list however. I think we should instead not set aria-orientation by default, and move the responsibility of a11y to the user. How does that sound?

**Comment by liamcmitchell-sc** [comment]
From what I understand, `aria-orientation` maps 1-1 to the vertical property in the adaptor so having it set by default does make sense. I appreciate that these components provide accessibility out of the box and I think it can be done.

The trouble is that the adaptor `vertical` state is controlled by an aria value.

To be done properly, a default value for `aria-orientation` could be inferred from a non-aria `orientation` or `vertical` prop **and** overridable by explicitly setting `aria-orientation`.

**Comment by moog16** [comment]
1. All the MDC List's should be "vertical", so having a vertical or orientation prop doesn't make sense to me. 
1. I agree that explicitly setting `aria-orientation` should be overridable.
1. Maybe `aria-orientation='vertical'` can be inferred if `props.tag !== 'ol' && props.tag !== 'ul' && props.tag !== 'dl' && props.role !== 'list'` OR we could use the MDN list's role. So if `props.role` === the following: 


scrollbar
listbox
combobox
menu
tree
separator
slider
tablist
toolbar

**Comment by liamcmitchell-sc** [comment]
Yes, I meant `MDCList.vertical`.

> All the MDC List's should be "vertical", so having a vertical or orientation prop doesn't make sense to me.
Agree, can't think of a case where this list would be used horizontally... but still this is supported in MDC web.

A whitelist would also work but overkill I think.

**Comment by moog16** [comment]
From the material.io spec, the image-list component is technically a "list". I don't think that semantically the list and image-list are the same though. 

And yes since its horizontal is supported, we should also support it. Your issue however is that its not meeting a11y. I also think the whitelist is overkill. How's about this case: `props.tag !== 'ol' && props.tag !== 'ul' && props.tag !== 'dl' && props.role !== 'list'` then?

**Comment by moog16** [comment]
You can also fix the setVertical if you'd like in the same PR. I just don't want to push the work on to you.

**Comment by liamcmitchell-sc** [comment]
Back from vacation.

> How's about this case: `props.tag !== 'ol' && props.tag !== 'ul' && props.tag !== 'dl' && props.role !== 'list'` then?

Only 4 elements have default roles that support `aria-orientation`: `datalist`, `hr`, `input` and `select`. I don't think any of them would be used as a list wrapper so it should be safe to ignore `props.tag`.

I think it's fair that if someone is overriding `role`, they know what they are doing and should also be responsible for providing `aria-orientation`. I don't see this as a common case though.

If we can ignore the above, we only care about the case when we apply role (for `checkboxList`/`radiogroup`).

This is how I would do it:

1. Add new prop `orientation` (`vertical | horizontal`, defaults to `vertical`) that replaces the current use of `aria-orientation`. **Breaking change.**
2. Render `aria-orientation` attribute only when all of the following are true
    1. orientation is not vertical (vertical is implicit)
    2. `props.role` is undefined (not overridden)
    3. we are applying role `group`/`radiogroup` (`checkboxList`/`radiogroup` is true)

Is there a concern about breaking changes?

**Comment by moog16** [comment]
@liamcmitchell-sc I think your list of operations makes sense to me. There is no concern for breaking changes, as we are still in 'beta'. However we'll communicate the breaking change through our changelog. How does that sound to you?

**Comment by liamcmitchell-sc** [comment]
Sounds good. Will work on the PR. CLA might take a while though...

**Comment by liamcmitchell-sc** [comment]
CLA signed, PR updated with latest master.

**Comment by liamcmitchell-sc** [comment]
PR merged
