### ISSUE TITLE
TextField: Label and Input Value stacked

### ISSUE THREAD

**Issue by larsrbak** [material-components/material-components-web-react#947]
If I first render the Textfield with the empty string and then later update it to something else the label and value will be stacked as shown in the image.

![Screenshot from 2019-06-22 14-09-28](https://user-images.githubusercontent.com/5303034/59963791-6b080a00-94f8-11e9-8748-940b8bb6f383.png)

Simplest reconstruction: 
```
const App: React.FC = () => {

  const [ value, setValue ] = React.useState('');

  useEffect(() => {
    setValue('alpha')
  }, [])

  return (
    <TextField label='Dog' >
      <Input value={value} />
    </TextField>
  );
}
```

or see: <https://github.com/larsrbak/mdc-react-textfield-issue>

**Comment by moog16** [comment]
I believe that this is the same [issue](https://github.com/material-components/material-components-web-react/issues/895). A fix will go out with rc0.14.0 (on 6/25/19 - tomorrow). Thanks!
