### ISSUE TITLE
Text field as password field?

### ISSUE THREAD

**Issue by cdevroe** [material-components/material-components-web-react#949]
My apologies in advance if I'm heading down the incorrect path with this question. Does the current Text Field web component _not_ allow for type to be password?

I'm creating a login form and would prefer to have the password field be type password.

**Comment by moog16** [comment]
Please see [example](https://stackblitz.com/edit/react-blcps3?file=index.js)

**Comment by cdevroe** [comment]
@moog16 Thank you for your quick response. Should [the docs](https://github.com/material-components/material-components-web-react/tree/master/packages/text-field) be updated to include the type prop on the input? Or is it just assumed?

Thanks.

**Comment by moog16** [comment]
I think it is assumed, but if it was not clear to you then it may not be clear to others. Please feel free to open a PR :)
