### ISSUE TITLE
Tab/TabBar ripple is is not required, Just need underline indicator & ripple effect should go after pressed

### ISSUE THREAD

**Issue by shb001** [material-components/material-components-web-react#950]
Hi 
I don't need ripple effect when I press the tab instead I only need indicator and ripple effect should go after the tab is active/pressed.
Please suggest if this is possible.
thanks in advance.

**Comment by moog16** [comment]
What do you mean "ripple effect should go after the tab is active/pressed.". Are you saying you only want the hover/focused state?

**Comment by shb001** [comment]
> What do you mean "ripple effect should go after the tab is active/pressed.". Are you saying you only want the hover/focused state?

Hi Thanks for the quick reply. I mean something like in the link below under Behaviour section. Please click on the video "Tap a tab".  I want the same kind of behaviour. After the tab is pressed I only want to have indicator and the colored label not the background. It should give the color effect like FAB button but should disappear immediately. Please have a look at the video under section behaviour. many thanks in advance.
https://material.io/design/components/tabs.html#behavior

**Comment by moog16** [comment]
So you don't want the background "ripple" effect?

Currently there is no way to do remove it as the ripple is [hard coded](https://github.com/material-components/material-components-web-react/blob/master/packages/tab/index.tsx#L221) into the Tab component.

**Comment by shb001** [comment]
> So you don't want the background "ripple" effect?
> 
> Currently there is no way to do remove it as the ripple is [hard coded](https://github.com/material-components/material-components-web-react/blob/master/packages/tab/index.tsx#L221) into the Tab component.

@moog16 thanks for the information.

**Comment by moog16** [comment]
Closing since there is no action to take here.
