### ISSUE TITLE
react-button 0.14.0 broken in SSR due to window usage

### ISSUE THREAD

**Issue by renanbatel** [material-components/material-components-web-react#954]
Just got the new version (0.14.0) of react-button and I see that `window` is being used on the .js dist file. So I can't use it on my server rendered react app (next.js), 0.13.0 works fine.

**Comment by jdaly13** [comment]
I have the same issue using react-card - also downgrading to 0.13.0 works fine for me as well.

**Comment by moog16** [comment]
Thanks for opening the issue. I'll look into fixing this.

**Comment by moog16** [comment]
please try v0.14.1
