### ISSUE TITLE
fix(typescript) remove extraneous imports

### ISSUE THREAD

**Issue by arichiv** [material-components/material-components-web-react#955]
https://github.com/material-components/material-components-web-react/pull/953 adds a bunch of imports to fix an error in typescript type expansion. They should be removed at some point.

Each one looks like:
```
import {
  [...]
  // @ts-ignore TODO(issues/955) Remove once possible
  RippledComponentProps, // eslint-disable-line @typescript-eslint/no-unused-vars
} from '@material/react-ripple';
```

Each one should be reduced to:
```
import {
  [...]
} from '@material/react-ripple';
```

**Comment by arichiv** [comment]
@moog16 I traced this to a typescript error not unlike https://github.com/microsoft/TypeScript/pull/24874 (cc: @weswigham)

If we do not explicitly import `RippledComponentProps` the resulting [typefile](https://termbin.com/w4ez) attempts a relative import at the bottom (`import("../ripple").RippledComponentProps`).

If we do explicitly import `RippledComponentProps` (and use/export it as required to avoid lint errors) the resulting [typefile](https://termbin.com/6ow4) is able to directly use the imported type (`RippledComponentProps`).

This appears to be an issue in typescript resolution/expansion itself. The import at the top is left alone, but the generated one at the bottom will default to a relative import.

**Comment by moog16** [comment]
Thanks for doing some more investigation. It sounds like this is a TypeScript bug then? We can leave this open until there is a fix and we update to that version. How does that sound?
