### ISSUE TITLE
Blinking except for the first element in `input chips`

### ISSUE THREAD

**Issue by TroyTae** [material-components/material-components-web-react#959]
![Jul-02-2019 01-22-23](https://user-images.githubusercontent.com/20078201/60451883-1d15a380-9c68-11e9-9215-952e3fb05420.gif)
When delete chip, every chips are blinking (exclude first chip).
I guess this isn't web issue, only react.

**Comment by moog16** [comment]
Thanks for opening! Confirmed an issue...looks like the click should not be propagated.

**Comment by TroyTae** [comment]
I don't know why first element is fine.
But I guess animation(`mdc-chip-set--input`) is executed every time.
<img width="1538" alt="스크린샷 2019-07-02 오후 10 22 42" src="https://user-images.githubusercontent.com/20078201/60516708-417d8880-9d19-11e9-8ffd-6a6cdffdd2ad.png">
