### ISSUE TITLE
Server takes too long to start

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#96]
Currently our screenshot tests take 200s on Travis to startup. We can decrease this time by decreasing the number of webpack configs we need to build. 

Related PR: https://github.com/material-components/material-components-web-react/pull/6

Proposed solution:
Use react-router to build a SPA of each page, which will result in one webpack config.

Known issues:

1. CBT requires a statically served site. *Solution*: use react-router's hash router, similar to the catalog pages. By doing this, we can host the demo pages from GCP without having an app server like nGinx.
1. CSS Name collisions. *Solution*: use css modules to obfuscate css classnames. When using css-loader from webpack, its a 1 line change to turn this feature on/off. Collisions will be near impossible, especially given we only have a few pages. If a naming collision does occur, we can increase the size of the hash (decreasing statistical chance of collision).

**Comment by moog16** [comment]
Related PR: https://github.com/material-components/material-components-web-react/pull/6

**Comment by lynnjepsen** [comment]
Steps to reproduce
* run `npm run start`

Expected Behavior
* the server should start in less than 10s (ideally 😁)

Actual Behavior
* the server takes at least 200s to start (☹️)

**Comment by lynnjepsen** [comment]
we're going to just make it one big entry point in webpack, and use react-router. This should significantly reduce the webpack compile time.
