### ISSUE TITLE
react-text-field npm package is empty

### ISSUE THREAD

**Issue by thdk** [material-components/material-components-web-react#969]
Seems the latest npm package for 0.14.1 is empty.

![image](https://user-images.githubusercontent.com/4201102/61001222-7d3ed080-a35f-11e9-9044-655890d68b79.png)

**Comment by moog16** [comment]
@thdk I think your VSCode probably hasn't updated. You should look directly in your directories/folders. 

A good place to check is unpkg:
https://unpkg.com/@material/react-text-field@0.14.1/dist/index.js
https://unpkg.com/@material/react-text-field@0.14.1/index.tsx
https://unpkg.com/@material/react-text-field@0.14.1/index.scss

It seems to be there.
