### ISSUE TITLE
MaterialIcon not rendering (Firefox)

### ISSUE THREAD

**Issue by qs-labs** [material-components/material-components-web-react#971]
The [MaterialIcon](https://github.com/material-components/material-components-web-react/tree/master/packages/material-icon) component does not properly render in Firefox.

Demonstrated with the [roses](https://github.com/material-components/material-components-web-react/tree/master/examples/roses) example project:
**Firefox (68.0 (64-bit))**
![image](https://user-images.githubusercontent.com/38405319/61073290-1c58dc00-a3e3-11e9-963b-8cb9586f6db4.png)
**Chrome (75.0.3770.100 (Official Build) (64-bit))**
![image](https://user-images.githubusercontent.com/38405319/61073453-778ace80-a3e3-11e9-978b-7766fcd546c5.png)
**IE (11.557.17763.0)**
![image](https://user-images.githubusercontent.com/38405319/61121568-88802200-a46d-11e9-86aa-fbaa995996e4.png)

**Comment by qs-labs** [comment]
Appears to have resolved itself, perhaps it was a Firefox issue?

**Comment by moog16** [comment]
Strange thanks for checking back in :)
