### ISSUE TITLE
About Repository Maintenance

### ISSUE THREAD

**Issue by TroyTae** [material-components/material-components-web-react#985]
Hello!

I am a contributor and user of this repository.
Thank you for making a good project.
But it seems this project is not maintain anymore.
So I want to clone this repository and maintain continuously.
Because I want to fix some issue and add features!
And let me know if someone comes as a maintainer, I'll provide all of code that I written.

Thank you :)

https://github.com/TroyTae/material-components-web-react

**Comment by TroyTae** [comment]
https://github.com/TroyTae/material-components-web-react

**Comment by liamcmitchell-sc** [comment]
Maybe they are all on vacation :)

If you are forking, use the GitHub fork feature so that you keep the git history and changes can be shared between repos.

**Comment by TroyTae** [comment]
@liamcmitchell-sc 
Thank you for your advice!
But I didn't fork this repository intentionally.
Because I don't have publish authority of this package and I'm not enterprise account.
So I changed some structure for npm publish...
Anyway I was planning to use cherry-pick for sharing.
Do you have any other good idea? :)

**Comment by liamcmitchell-sc** [comment]
To keep history and different publish config, you could create a `release` branch in your fork. This branch would contain the different config. If you do all your work on master or any other branch *without* the config changes, you will be able to share these changes much easier with other forks. You would just have to merge your changes into the release branch each time you want to publish them.

**Comment by TroyTae** [comment]
@liamcmitchell-sc 
It's a good idea!
I'll try to do that :)
